In [1]:
#This example uses Python 2.7 and the python-request library.

from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'1000',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': 'f4e28ecd-264a-4797-8bc5-3f0b7d51211e'
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)
    # bhai sirf 1000 type krte hi shi aagya

{'status': {'timestamp': '2025-02-22T05:15:38.287Z', 'error_code': 0, 'error_message': None, 'elapsed': 29, 'credit_count': 5, 'notice': None, 'total_count': 10882}, 'data': [{'id': 1, 'name': 'Bitcoin', 'symbol': 'BTC', 'slug': 'bitcoin', 'num_market_pairs': 11957, 'date_added': '2010-07-13T00:00:00.000Z', 'tags': ['mineable', 'pow', 'sha-256', 'store-of-value', 'state-channel', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'binance-labs-portfolio', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'galaxy-digital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'bitcoin-ecosystem', 'ftx-bankruptcy-estate', '2017-2018-alt-season'], 'max_supply': 21000000, 'circulating_supply': 19827490, 'total_supply': 19827490, 'infinite_supply': False, 'platform': None, 'cmc_rank': 1, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 96378.92784704438, 'volume_24h': 49259813280.51931, 'volume_change_24h': 60.0964, 'percent_change_1h': -0.01669296, 'percent_change_24h': -1.93030493, 'percent_change_7d': -1.19951215, 'percent_change_30d': -5.62635675, 'percent_change_60d': 2.15591819, 'percent_change_90d': -1.99552261, 'market_cap': 1910952228097.9941, 'market_cap_dominance': 60.2185, 'fully_diluted_market_cap': 2023957484787.93, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'num_market_pairs': 9946, 'date_added': '2015-08-07T00:00:00.000Z', 'tags': ['pos', 'smart-contracts', 'ethereum-ecosystem', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'heco-ecosystem', 'binance-labs-portfolio', 'avalanche-ecosystem', 'solana-ecosystem', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'hashkey-capital-portfolio', 'kenetic-capital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'tezos-ecosystem', 'near-protocol-ecosystem', 'velas-ecosystem', 'ethereum-pow-ecosystem', 'osmosis-ecosystem', 'layer-1', 'ftx-bankruptcy-estate', 'zksync-era-ecosystem', 'viction-ecosystem', 'klaytn-ecosystem', 'sora-ecosystem', 'rsk-rbtc-ecosystem', 'starknet-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 120566328.15075894, 'total_supply': 120566328.15075894, 'infinite_supply': True, 'platform': None, 'cmc_rank': 2, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:13:00.000Z', 'quote': {'USD': {'price': 2679.2117757430833, 'volume_24h': 32893588980.549862, 'volume_change_24h': 118.0335, 'percent_change_1h': -0.04701526, 'percent_change_24h': -2.545865, 'percent_change_7d': -1.60765598, 'percent_change_30d': -16.43096798, 'percent_change_60d': -21.41088777, 'percent_change_90d': -21.69311188, 'market_cap': 323022726139.61816, 'market_cap_dominance': 10.1832, 'fully_diluted_market_cap': 323022726139.62, 'tvl': None, 'last_updated': '2025-02-22T05:13:00.000Z'}}}, {'id': 52, 'name': 'XRP', 'symbol': 'XRP', 'slug': 'xrp', 'num_market_pairs': 1541, 'date_added': '2013-08-04T00:00:00.000Z', 'tags': ['medium-of-exchange', 'enterprise-solutions', 'xrp-ecosystem', 'arrington-xrp-capital-portfolio', 'galaxy-digital-portfolio', 'a16z-portfolio', 'pantera-capital-portfolio', 'ftx-bankruptcy-estate', '2017-2018-alt-season', 'klaytn-ecosystem', 'made-in-america'], 'max_supply': 100000000000, 'circulating_supply': 57887806032, 'total_supply': 99986418374, 'infinite_supply': False, 'platform': None, 'cmc_rank': 3, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 2.5783476901051507, 'volume_24h': 5875494926.486849, 'volume_change_24h': 46.8178, 'percent_change_1h': 0.16772646, 'percent_change_24h': -2.91485456, 'percent_change_7d': -7.8951086, 'percent_change_30d': -17.58203024, 'percent_change_60d': 14.20847848, 'percent_change_90d': 75.72585766, 'market_cap': 149254890967.8622, 'market_cap_dominance': 4.7052, 'fully_diluted_market_cap': 257834769010.52, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 825, 'name': 'Tether USDt', 'symbol': 'USDT', 'slug': 'tether', 'num_market_pairs': 117647, 'date_added': '2015-02-25T00:00:00.000Z', 'tags': ['stablecoin', 'asset-backed-stablecoin', 'ethereum-ecosystem', 'waves-ecosystem', 'bitcoin-cash-ecosystem', 'heco-ecosystem', 'algorand-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'polygon-ecosystem', 'fantom-ecosystem', 'terra-ecosystem', 'tezos-ecosystem', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'celo-ecosystem', 'iotex-ecosystem', 'zilliqa-ecosystem', 'harmony-ecosystem', 'moonriver-ecosystem', 'cronos-ecosystem', 'injective-ecosystem', 'oasis-ecosystem', 'moonbeam-ecosystem', 'usd-stablecoin', 'xdc-ecosystem', 'everscale-ecosystem', 'velas-ecosystem', 'doge-chain-ecosystem', 'ethereum-pow-ecosystem', 'aptos-ecosystem', 'sui-ecosystem', 'optimism-ecosystem', 'canto-ecosystem', 'osmosis-ecosystem', 'zksync-era-ecosystem', 'pulsechain-ecosystem', 'sei-ecosystem', 'toncoin-ecosystem', 'fiat-stablecoin', 'viction-ecosystem', 'gnosis-chain-ecosystem', 'klaytn-ecosystem', 'okexchain-ecosystem', 'conflux-ecosystem', 'kcc-ecosystem', 'tron20-ecosystem', 'kardiachain-ecosystem', 'rsk-rbtc-ecosystem', 'telos-ecosystem', 'boba-network-ecosystem', 'fusion-network-ecosystem', 'hoo-smart-chain-ecosystem', 'secret-ecosystem', 'aurora-ecosystem', 'metis-andromeda-ecosystem', 'meter-ecosystem', 'fuse-ecosystem', 'syscoin-ecosystem', 'milkomeda-ecosystem', 'bitgert-ecosystem', 'astar-ecosystem', 'cube-network-ecosystem', 'thundercore-ecosystem', 'redlight-chain-ecosystem', 'core-ecosystem', 'polygon-zkevm-ecosystem', 'eos-evm-ecosystem', 'starknet-ecosystem', 'mantle-ecosystem', 'neon-evm-ecosystem', 'manta-pacific-ecosystem', 'scroll-ecosystem', 'x-layer-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 142489546124.8272, 'total_supply': 144566824343.61542, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0xdac17f958d2ee523a2206206994597c13d831ec7'}, 'infinite_supply': True, 'cmc_rank': 4, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:13:00.000Z', 'quote': {'USD': {'price': 1.0000115710382007, 'volume_24h': 109507521523.1073, 'volume_change_24h': 53.1297, 'percent_change_1h': -0.0231098, 'percent_change_24h': -0.016396, 'percent_change_7d': -0.01689862, 'percent_change_30d': 0.08062982, 'percent_change_60d': 0.14262507, 'percent_change_90d': -0.11551392, 'market_cap': 142491194876.80862, 'market_cap_dominance': 4.4902, 'fully_diluted_market_cap': 144568497131.86, 'tvl': None, 'last_updated': '2025-02-22T05:13:00.000Z'}}}, {'id': 1839, 'name': 'BNB', 'symbol': 'BNB', 'slug': 'bnb', 'num_market_pairs': 2372, 'date_added': '2017-07-25T00:00:00.000Z', 'tags': ['marketplace', 'centralized-exchange', 'payments', 'smart-contracts', 'ethereum-ecosystem', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'bnb-chain-ecosystem', 'layer-1', 'alleged-sec-securities', 'celsius-bankruptcy-estate'], 'max_supply': None, 'circulating_supply': 142476711.79, 'total_supply': 142476711.79, 'infinite_supply': False, 'platform': None, 'cmc_rank': 5, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 655.1940448312777, 'volume_24h': 1958804754.1220179, 'volume_change_24h': 21.9443, 'percent_change_1h': 0.62693813, 'percent_change_24h': 0.44583173, 'percent_change_7d': -0.50938787, 'percent_change_30d': -4.41736652, 'percent_change_60d': -5.21217733, 'percent_change_90d': -1.04603573, 'market_cap': 93349893091.95029, 'market_cap_dominance': 2.9422, 'fully_diluted_market_cap': 93349893091.95, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 5426, 'name': 'Solana', 'symbol': 'SOL', 'slug': 'solana', 'num_market_pairs': 841, 'date_added': '2020-04-10T00:00:00.000Z', 'tags': ['pos', 'platform', 'solana-ecosystem', 'cms-holdings-portfolio', 'kenetic-capital-portfolio', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'okx-ventures-portfolio', 'layer-1', 'ftx-bankruptcy-estate', 'alleged-sec-securities', 'cmc-crypto-awards-2024', 'made-in-america'], 'max_supply': None, 'circulating_supply': 488731192.6180695, 'total_supply': 594683033.4978944, 'infinite_supply': True, 'platform': None, 'cmc_rank': 6, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:13:00.000Z', 'quote': {'USD': {'price': 171.51565019333486, 'volume_24h': 4662164111.892372, 'volume_change_24h': 42.2652, 'percent_change_1h': 0.60433417, 'percent_change_24h': -1.70025789, 'percent_change_7d': -13.22186822, 'percent_change_30d': -30.98332645, 'percent_change_60d': -10.1260034, 'percent_change_90d': -33.36844932, 'market_cap': 83825048271.65218, 'market_cap_dominance': 2.6426, 'fully_diluted_market_cap': 101997447149.34, 'tvl': None, 'last_updated': '2025-02-22T05:13:00.000Z'}}}, {'id': 3408, 'name': 'USDC', 'symbol': 'USDC', 'slug': 'usd-coin', 'num_market_pairs': 25894, 'date_added': '2018-10-08T00:00:00.000Z', 'tags': ['medium-of-exchange', 'stablecoin', 'asset-backed-stablecoin', 'ethereum-ecosystem', 'waves-ecosystem', 'bitcoin-cash-ecosystem', 'wanchain-ecosystem', 'coinbase-ventures-portfolio', 'algorand-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'hedera-hashgraph-ecosystem', 'polygon-ecosystem', 'terra-ecosystem', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'celo-ecosystem', 'iotex-ecosystem', 'harmony-ecosystem', 'moonriver-ecosystem', 'cronos-ecosystem', 'injective-ecosystem', 'oasis-ecosystem', 'moonbeam-ecosystem', 'usd-stablecoin', 'everscale-ecosystem', 'velas-ecosystem', 'doge-chain-ecosystem', 'ethereum-pow-ecosystem', 'aptos-ecosystem', 'sui-ecosystem', 'optimism-ecosystem', 'canto-ecosystem', 'osmosis-ecosystem', 'zksync-era-ecosystem', 'pulsechain-ecosystem', 'base-ecosystem', 'sei-ecosystem', 'multiversx-ecosystem', 'fiat-stablecoin', 'viction-ecosystem', 'gnosis-chain-ecosystem', 'okexchain-ecosystem', 'conflux-ecosystem', 'kcc-ecosystem', 'tron20-ecosystem', 'kardiachain-ecosystem', 'telos-ecosystem', 'ronin-ecosystem', 'boba-network-ecosystem', 'kava-ecosystem', 'secret-ecosystem', 'aurora-ecosystem', 'metis-andromeda-ecosystem', 'meter-ecosystem', 'fuse-ecosystem', 'elastos-ecosystem', 'syscoin-ecosystem', 'milkomeda-ecosystem', 'evmos-ecosystem', 'bitgert-ecosystem', 'astar-ecosystem', 'thundercore-ecosystem', 'tomb-chain-ecosystem', 'wemix-ecosystem', 'sx-network-ecosystem', 'godwoken-ecosystem', 'energi-ecosystem', 'core-ecosystem', 'polygon-zkevm-ecosystem', 'starknet-ecosystem', 'mantle-ecosystem', 'neon-evm-ecosystem', 'scroll-ecosystem', 'shido-network-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 57186437907.32239, 'total_supply': 57186437907.32239, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'}, 'infinite_supply': False, 'cmc_rank': 7, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:13:00.000Z', 'quote': {'USD': {'price': 1.000084149629321, 'volume_24h': 10792492682.756119, 'volume_change_24h': 47.3407, 'percent_change_1h': 0.00306625, 'percent_change_24h': 0.01537222, 'percent_change_7d': 0.0060192, 'percent_change_30d': 0.01746697, 'percent_change_60d': 0.00513977, 'percent_change_90d': 0.01939208, 'market_cap': 57191250124.87447, 'market_cap_dominance': 1.8029, 'fully_diluted_market_cap': 57191250124.87, 'tvl': None, 'last_updated': '2025-02-22T05:13:00.000Z'}}}, {'id': 74, 'name': 'Dogecoin', 'symbol': 'DOGE', 'slug': 'dogecoin', 'num_market_pairs': 1168, 'date_added': '2013-12-15T00:00:00.000Z', 'tags': ['mineable', 'pow', 'scrypt', 'medium-of-exchange', 'memes', 'payments', 'doggone-doggerel', 'doge-chain-ecosystem', 'ftx-bankruptcy-estate', 'made-in-america'], 'max_supply': None, 'circulating_supply': 148147416383.70523, 'total_supply': 148147416383.70523, 'infinite_supply': True, 'platform': None, 'cmc_rank': 8, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 0.24278259988516418, 'volume_24h': 2098794204.5766432, 'volume_change_24h': 89.8403, 'percent_change_1h': 0.35953641, 'percent_change_24h': -4.19709742, 'percent_change_7d': -12.95317702, 'percent_change_30d': -30.92076159, 'percent_change_60d': -24.76361462, 'percent_change_90d': -44.70164818, 'market_cap': 35967614915.90592, 'market_cap_dominance': 1.1334, 'fully_diluted_market_cap': 35967614915.91, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 2010, 'name': 'Cardano', 'symbol': 'ADA', 'slug': 'cardano', 'num_market_pairs': 1465, 'date_added': '2017-10-01T00:00:00.000Z', 'tags': ['dpos', 'pos', 'platform', 'research', 'smart-contracts', 'staking', 'cardano-ecosystem', 'cardano', 'layer-1', 'alleged-sec-securities', '2017-2018-alt-season', 'made-in-america'], 'max_supply': 45000000000, 'circulating_supply': 35204786637.28696, 'total_supply': 44994955922.926414, 'infinite_supply': False, 'platform': None, 'cmc_rank': 9, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 0.7693568597783291, 'volume_24h': 990351668.9415513, 'volume_change_24h': 48.3532, 'percent_change_1h': 0.36295079, 'percent_change_24h': -4.27901392, 'percent_change_7d': -4.87763238, 'percent_change_30d': -20.55742996, 'percent_change_60d': -15.70458027, 'percent_change_90d': -27.77395837, 'market_cap': 27085044096.429176, 'market_cap_dominance': 0.8538, 'fully_diluted_market_cap': 34621058690.02, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 1958, 'name': 'TRON', 'symbol': 'TRX', 'slug': 'tron', 'num_market_pairs': 1123, 'date_added': '2017-09-13T00:00:00.000Z', 'tags': ['media', 'payments', 'ethereum-ecosystem', 'tron-ecosystem', 'layer-1', 'dwf-labs-portfolio', 'alleged-sec-securities', '2017-2018-alt-season', 'tron20-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 86083864751.77873, 'total_supply': 86083885090.44815, 'infinite_supply': True, 'platform': None, 'cmc_rank': 10, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 0.23790474138285556, 'volume_24h': 643890786.1278726, 'volume_change_24h': 28.6095, 'percent_change_1h': -0.36091207, 'percent_change_24h': -4.8104999, 'percent_change_7d': 2.12144996, 'percent_change_30d': -4.11169474, 'percent_change_60d': -5.63882887, 'percent_change_90d': 10.60133179, 'market_cap': 20479759581.008633, 'market_cap_dominance': 0.6456, 'fully_diluted_market_cap': 20479764419.67, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 1975, 'name': 'Chainlink', 'symbol': 'LINK', 'slug': 'chainlink', 'num_market_pairs': 1932, 'date_added': '2017-09-20T00:00:00.000Z', 'tags': ['platform', 'defi', 'oracles', 'smart-contracts', 'ethereum-ecosystem', 'substrate', 'polkadot', 'heco-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'framework-ventures-portfolio', 'polygon-ecosystem', 'fantom-ecosystem', 'cardano-ecosystem', 'terra-ecosystem', 'web3', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'cardano', 'injective-ecosystem', 'bnb-chain-ecosystem', 'optimism-ecosystem', 'real-world-assets', 'celsius-bankruptcy-estate', 'gnosis-chain-ecosystem', 'sora-ecosystem', 'hoo-smart-chain-ecosystem', 'milkomeda-ecosystem', 'energi-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 638099970.4527867, 'total_supply': 1000000000, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0x514910771af9ca656af840dff83e8264ecf986ca'}, 'infinite_supply': False, 'cmc_rank': 11, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 17.566408897351824, 'volume_24h': 711000566.0537516, 'volume_change_24h': 93.0044, 'percent_change_1h': 0.42629476, 'percent_change_24h': -3.66003217, 'percent_change_7d': -10.25129051, 'percent_change_30d': -28.79215604, 'percent_change_60d': -27.34689762, 'percent_change_90d': -1.55296438, 'market_cap': 11209124998.361769, 'market_cap_dominance': 0.3534, 'fully_diluted_market_cap': 17566408897.35, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 5805, 'name': 'Avalanche', 'symbol': 'AVAX', 'slug': 'avalanche', 'num_market_pairs': 867, 'date_added': '2020-07-13T00:00:00.000Z', 'tags': ['defi', 'smart-contracts', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'avalanche-ecosystem', 'cms-holdings-portfolio', 'dragonfly-capital-portfolio', 'moonbeam-ecosystem', 'real-world-assets', 'layer-1', 'zksync-era-ecosystem', 'klaytn-ecosystem', 'made-in-america'], 'max_supply': 715748719, 'circulating_supply': 413958757.4465295, 'total_supply': 450628257.4465295, 'infinite_supply': False, 'platform': None, 'cmc_rank': 12, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:13:00.000Z', 'quote': {'USD': {'price': 25.257856684362164, 'volume_24h': 659068492.8583506, 'volume_change_24h': 93.2099, 'percent_change_1h': 0.05205804, 'percent_change_24h': 1.01942054, 'percent_change_7d': -5.43407269, 'percent_change_30d': -29.40086874, 'percent_change_60d': -34.95831718, 'percent_change_90d': -40.75199533, 'market_cap': 10455710968.821081, 'market_cap_dominance': 0.3296, 'fully_diluted_market_cap': 18078278566.52, 'tvl': None, 'last_updated': '2025-02-22T05:13:00.000Z'}}}, {'id': 20947, 'name': 'Sui', 'symbol': 'SUI', 'slug': 'sui', 'num_market_pairs': 559, 'date_added': '2022-07-12T08:03:11.000Z', 'tags': ['binance-launchpool', 'coinbase-ventures-portfolio', 'binance-labs-portfolio', 'electric-capital-portfolio', 'a16z-portfolio', 'sui-ecosystem', 'layer-1', 'move-vm', 'cmc-crypto-yearbook-2024-2025', 'made-in-america'], 'max_supply': 10000000000, 'circulating_supply': 3089707194.508888, 'total_supply': 10000000000, 'infinite_supply': False, 'platform': None, 'cmc_rank': 13, 'self_reported_circulating_supply': 3089707194.508888, 'self_reported_market_cap': 10386756211.506752, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:13:00.000Z', 'quote': {'USD': {'price': 3.361728331398645, 'volume_24h': 1239635358.0341027, 'volume_change_24h': 27.4421, 'percent_change_1h': 0.87859727, 'percent_change_24h': -4.98148823, 'percent_change_7d': -3.95446083, 'percent_change_30d': -23

In [2]:
type(data)

dict

In [3]:
import pandas as pd 
pd.set_option('display.max_columns',None)
pd.set_option ('display.max_rows',None)

In [4]:
df = pd.json_normalize(data['data'])
df['timestamp']= pd.to_datetime('now')
df

        id                                               name     symbol  \
0        1                                            Bitcoin        BTC
1     1027                                           Ethereum        ETH
2       52                                                XRP        XRP
3      825                                        Tether USDt       USDT
4     1839                                                BNB        BNB
5     5426                                             Solana        SOL
6     3408                                               USDC       USDC
7       74                                           Dogecoin       DOGE
8     2010                                            Cardano        ADA
9     1958                                               TRON        TRX
10    1975                                          Chainlink       LINK
11    5805                                          Avalanche       AVAX
12   20947                                                Sui        SUI
13     512                                            Stellar        XLM
14       2                                           Litecoin        LTC
15    4642                                             Hedera       HBAR
16    3957                                       UNUS SED LEO        LEO
17   11419                                            Toncoin        TON
18    5994                                          Shiba Inu       SHIB
19   32196                                        Hyperliquid       HYPE
20    6636                                           Polkadot        DOT
21    6536                                             MANTRA         OM
22    1831                                       Bitcoin Cash        BCH
23   11092                                       Bitget Token        BGB
24   29470                                        Ethena USDe       USDe
25    4943                                                Dai        DAI
26    7083                                            Uniswap        UNI
27     328                                             Monero        XMR
28    6535                                      NEAR Protocol       NEAR
29   24478                                               Pepe       PEPE
30   22974                                          Bittensor        TAO
31    7278                                               Aave       AAVE
32   21159                                               Ondo       ONDO
33   21794                                              Aptos        APT
34    8916                                  Internet Computer        ICP
35   35336                                     OFFICIAL TRUMP      TRUMP
36    1321                                   Ethereum Classic        ETC
37   27075                                             Mantle        MNT
38    3897                                                OKB        OKB
39   20396                                              Kaspa        KAS
40    3077                                            VeChain        VET
41   28321                                  POL (prev. MATIC)        POL
42   32684                                  Sonic (prev. FTM)          S
43    4030                                           Algorand       ALGO
44    3635                                             Cronos        CRO
45    5690                                             Render     RENDER
46    2280                                           Filecoin        FIL
47   29210                                            Jupiter        JUP
48   11841                                           Arbitrum        ARB
49    4269                                          GateToken         GT
50   26081                                  First Digital USD      FDUSD
51   22861                                           Celestia        TIA
52    3794                                             Cosmos       ATOM
53    3773              Artificial Superintelligence Alliance        FET
54   11840                                           Optimism         OP
55    7326                                               DeXe       DEXE
56    7226                                          Injective        INJ
57    2087                                       KuCoin Token        KCS
58    8000                                           Lido DAO        LDO
59   30171                                             Ethena        ENA
60    4847                                             Stacks        STX
61    2634                                        XDC Network        XDC
62    2416                                      Theta Network      THETA
63   23149                                                Sei        SEI
64    6719                                          The Graph        GRT
65    1518                                              Maker        MKR
66   13502                                          Worldcoin        WLD
67    8526                                            Raydium        RAY
68   10603                                          Immutable        IMX
69   23095                                               Bonk       BONK
70    7950                                              Flare        FLR
71    3155                                              Quant        QNT
72   32452                                           Movement       MOVE
73   35626                                              Story         IP
74    8425                                          JasmyCoin      JASMY
75    1765                                                EOS        EOS
76   13855                              Ethereum Name Service        ENS
77    2011                                              Tezos        XTZ
78   10804                                              FLOKI      FLOKI
79   28177                                       Pyth Network       PYTH
80    6210                                        The Sandbox       SAND
81    2694                                               Nexo       NEXO
82   28541                                               Jito        JTO
83    7080                                               Gala       GALA
84   16086                                   BitTorrent [New]        BTT
85    4558                                               Flow       FLOW
86    1720                                               IOTA       IOTA
87   32880                                               Kaia       KAIA
88   24647                                          Berachain       BERA
89   27772                                         PayPal USD      PYUSD
90    1376                                                Neo        NEO
91   29420                                  Virtuals Protocol    VIRTUAL
92   14101                                              Ronin        RON
93    3602                                         Bitcoin SV        BSV
94    5176                                        Tether Gold       XAUt
95    7186                                        PancakeSwap       CAKE
96   35347                              Official Melania Meme    MELANIA
97    6783                                      Axie Infinity        AXS
98    6892                                         MultiversX       EGLD
99    6538                                    Curve DAO Token        CRV
100  28081                                            SPX6900        SPX
101  28752                                          dogwifhat        WIF
102   5632                                            Arweave         AR
103   5665                                             Helium        HNT
104   1966                                       Decentraland       MANA
105   4195                                          FTX Token        FTT
106   4705                                           PAX Gold       PAXG
107  29270                                  Aerodrome Finance       AERO
108   7334                                            Conflux        CFX
109  18679                                           Onyxcoin        XCN
110  22691                                           Starknet       STRK
111  28324                                               dYdX       DYDX
112   1437                                              Zcash        ZEC
113   3890                                            Polygon      MATIC
114   9481                                             Pendle     PENDLE
115  23254                                               Core       CORE
116  10791                                              eCash        XEC
117  34466                                     Pudgy Penguins      PENGU
118  32956                                              Grass      GRASS
119  18876                                            ApeCoin        APE
120   9104                                       AIOZ Network       AIOZ
121   2563                                            TrueUSD       TUSD
122   4066                                             Chiliz        CHZ
123   3964                                     Reserve Rights        RSR
124  34104                                             Morpho     MORPHO
125   5692                                           Compound       COMP
126  28298                                               Beam       BEAM
127  33391                                  DeepBook Protocol       DEEP
128  29743                                      Brett (Based)      BRETT
129  29587                                           Wormhole          W
130   4846                                               Kava       KAVA
131  30494                                         EigenLayer      EIGEN
132   1659                                             Gnosis        GNO
133   9816                                             APENFT        NFT
134   6945                                                Amp        AMP
135   7431                                      Akash Network        AKT
136  23635                                            BinaryX        BNX
137  17799                                             Axelar        AXL
138   4157                                          THORChain       RUNE
139   5964                                 Trust Wallet Token        TWT
140   8646                                               Mina       MINA
141  35763                                              KAITO      KAITO
142  34026                                              ai16z      AI16Z
143   4172                                      Terra Classic       LUNC
144  24091                                             ZKsync         ZK
145   8104                                      1inch Network      1INCH
146   3822                                         Theta Fuel      TFUEL
147   8290                                         SuperVerse      SUPER
148  23121                                               Blur       BLUR
149   5488                                               JUST        JST
150   2586                                          Synthetix        SNX
151    131                                               Dash       DASH
152   5034                                             Kusama        KSM
153  12885                                              Astar       ASTR
154   8119                                            SafePal        SFP
155  33597                                           Fartcoin   FARTCOIN
156   5198                                         Creditcoin        CTC
157   4041                                           MX Token         MX
158  26997                                          LayerZero        ZRO
159   1684                                               Qtum       QTUM
160   7548                                              WEMIX      WEMIX
161   4948                                     Nervos Network        CKB
162  28850                                            Notcoin        NOT
163   7653                                              Oasis       ROSE
164   6958                                        Alchemy Pay        ACH
165   3012                                       VeThor Token       VTHO
166   1455                                              Golem        GLM
167  21585                                               Safe       SAFE
168   2469                                            Zilliqa        ZIL
169  27659                                           Mog Coin        MOG
170   3640                                           Livepeer        LPT
171   1697                              Basic Attention Token        BAT
172   2682                                               Holo        HOT
173  25028                                               ORDI       ORDI
174   1896                                        0x Protocol        ZRX
175  21846                                           SPACE ID         ID
176  10407                                     Baby Doge Coin   BabyDoge
177  27750                                              Toshi      TOSHI
178  29814                                           ether.fi      ETHFI
179  28194                                    SATS (Ordinals)       SATS
180   1785                                                Gas        GAS
181   9903                                     Convex Finance        CVX
182  30083                                             Aethir        ATH
183  30126                                cat in a dogs world        MEW
184  31526                                       Moca Network       MOCA
185   5567                                               Celo       CELO
186   2467                                        OriginTrail       TRAC
187  30063                                           Gigachad       GIGA
188   3783                                               Ankr       ANKR
189   1042                                            Siacoin         SC
190  12220                                            Osmosis       OSMO
191   3945                                            Harmony        ONE
192   6758                                          SushiSwap      SUSHI
193  24911                                              Turbo      TURBO
194  28782                                       Popcat (SOL)     POPCAT
195  29779                                  Polyhedra Network        ZKJ
196   1168                                             Decred        DCR
197   7501                                                WOO        WOO
198  17751                                          Threshold          T
199   8536                                       Mask Network       MASK
200  32531                                           RYO Coin        RYO
201  22615                                          Fasttoken        FTN
202  32307                                          Usual USD       USD0
203   2394                                            Telcoin        TEL
204  27765                                              Zeebu        ZBU
205  29839                                    Meta Games Coin        MGC
206  28293                                             Ultima     ULTIMA
207  20787                                             Fellaz        FLZ
208   3871                                             Newton        NEW
209  33553                                          insurance  INSURANCE
210   6952                                               Frax       FRAX
211   3987                                             Beldex        BDX
212  34595                                             RZcoin         RZ
213  23054                                            Cheelee      CHEEL
214  33110                                        Solana Swap        SOS
215   8534                                            Chintai       CHEX
216  29256                               Ondo US Dollar Yield       USDY
217  25264                                               Snek       SNEK
218  34330                                             Freysa        FAI
219  30933                                      Dog (Bitcoin)        DOG
220  31024                                       Elixir deUSD      DEUSD
221  32968                                      AI Companions        AIC
222   2499                                          SwissBorg       BORG
223  23951                                             Staika       STIK
224   9025                                              Tribe      TRIBE
225  35268                                    GoPlus Security        GPS
226  32257                                             UXLINK     UXLINK
227   2130                                         Enjin Coin        ENJ
228   2299                                               aelf        ELF
229   2577                                          Ravencoin        RVN
230   5031                                   MimbleWimbleCoin        MWC
231  21259                                          ZetaChain       ZETA
232  34926                                     AI Rig Complex        ARC
233   2496                                           Polymath       POLY
234  21870                                           Metaplex       MPLX
235  35209                                      Jewelry Token    JEWELRY
236   5691                                              SKALE        SKL
237   2765                                                XYO        XYO
238   1698                                            Horizen        ZEN
239   5864                                      yearn.finance        YFI
240  32197                                         Magic Eden         ME
241    873                                                NEM        XEM
242  23711                                      Echelon Prime      PRIME
243  31278                                              Drift      DRIFT
244  15271                                       Rollbit Coin        RLB
245  11857                                                GMX        GMX
246  29835                                             io.net         IO
247  24554                                            Bazaars        BZR
248  21296                                        EthereumPoW       ETHW
249  34619                                               Vana       VANA
250   1274                                              Waves      WAVES
251  10180                                           GoМining   GOMINING
252  28654                                               UPCX        UPC
253  18069                                                GMT        GMT
254   9258                                               Chia        XCH
255   1934                                           Loopring        LRC
256  29884                                     Destra Network      DSYNC
257   2777                                              IoTeX       IOTX
258   4006                                                STP       STPT
259  19891                                               USDD       USDD
260  10529                                          Sun [New]        SUN
261  33566                            Act I : The AI Prophecy        ACT
262  20314                                              Terra       LUNA
263   2566                                           Ontology        ONT
264  27599                                           APF coin       APFC
265  28380                                      GoldPro Token       GPRO
266  22850                                         Hivemapper      HONEY
267  32120                                            Gravity          G
268  12573                                          Clearpool      CPOOL
269   5370                                               Hive       HIVE
270  34103                                              aixbt      AIXBT
271  34812                                       Bio Protocol        BIO

# automating crypto website api full (51:13 in playlist)

In [5]:
#This example uses Python 2.7 and the python-request library.

from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'15',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': 'f4e28ecd-264a-4797-8bc5-3f0b7d51211e'
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)
    # bhai sirf 1000 type krte hi shi aagya

{'status': {'timestamp': '2025-02-22T05:16:03.221Z', 'error_code': 0, 'error_message': None, 'elapsed': 28, 'credit_count': 1, 'notice': None, 'total_count': 10882}, 'data': [{'id': 1, 'name': 'Bitcoin', 'symbol': 'BTC', 'slug': 'bitcoin', 'num_market_pairs': 11957, 'date_added': '2010-07-13T00:00:00.000Z', 'tags': ['mineable', 'pow', 'sha-256', 'store-of-value', 'state-channel', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'binance-labs-portfolio', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'galaxy-digital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'bitcoin-ecosystem', 'ftx-bankruptcy-estate', '2017-2018-alt-season'], 'max_supply': 21000000, 'circulating_supply': 19827490, 'total_supply': 19827490, 'infinite_supply': False, 'platform': None, 'cmc_rank': 1, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 96419.16758201279, 'volume_24h': 49383585193.03519, 'volume_change_24h': 60.261, 'percent_change_1h': -0.0035905, 'percent_change_24h': -1.90005081, 'percent_change_7d': -1.10089495, 'percent_change_30d': -5.60851584, 'percent_change_60d': 2.1515109, 'percent_change_90d': -1.94478304, 'market_cap': 1911750081040.6826, 'market_cap_dominance': 60.2542, 'fully_diluted_market_cap': 2024802519222.27, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'num_market_pairs': 9946, 'date_added': '2015-08-07T00:00:00.000Z', 'tags': ['pos', 'smart-contracts', 'ethereum-ecosystem', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'heco-ecosystem', 'binance-labs-portfolio', 'avalanche-ecosystem', 'solana-ecosystem', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'hashkey-capital-portfolio', 'kenetic-capital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'tezos-ecosystem', 'near-protocol-ecosystem', 'velas-ecosystem', 'ethereum-pow-ecosystem', 'osmosis-ecosystem', 'layer-1', 'ftx-bankruptcy-estate', 'zksync-era-ecosystem', 'viction-ecosystem', 'klaytn-ecosystem', 'sora-ecosystem', 'rsk-rbtc-ecosystem', 'starknet-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 120566328.15075894, 'total_supply': 120566328.15075894, 'infinite_supply': True, 'platform': None, 'cmc_rank': 2, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 2678.2370816001753, 'volume_24h': 32857097693.649025, 'volume_change_24h': 117.8005, 'percent_change_1h': -0.09649823, 'percent_change_24h': -2.59173822, 'percent_change_7d': -1.59996845, 'percent_change_30d': -16.4705, 'percent_change_60d': -21.45431962, 'percent_change_90d': -21.75045818, 'market_cap': 322905210845.7377, 'market_cap_dominance': 10.1795, 'fully_diluted_market_cap': 322905210845.74, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 52, 'name': 'XRP', 'symbol': 'XRP', 'slug': 'xrp', 'num_market_pairs': 1541, 'date_added': '2013-08-04T00:00:00.000Z', 'tags': ['medium-of-exchange', 'enterprise-solutions', 'xrp-ecosystem', 'arrington-xrp-capital-portfolio', 'galaxy-digital-portfolio', 'a16z-portfolio', 'pantera-capital-portfolio', 'ftx-bankruptcy-estate', '2017-2018-alt-season', 'klaytn-ecosystem', 'made-in-america'], 'max_supply': 100000000000, 'circulating_supply': 57887806032, 'total_supply': 99986418374, 'infinite_supply': False, 'platform': None, 'cmc_rank': 3, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 2.5779426679349013, 'volume_24h': 5875942030.6162815, 'volume_change_24h': 46.8163, 'percent_change_1h': 0.14726143, 'percent_change_24h': -2.92832621, 'percent_change_7d': -7.93537041, 'percent_change_30d': -17.59508321, 'percent_change_60d': 14.22417032, 'percent_change_90d': 75.45451876, 'market_cap': 149231445123.03217, 'market_cap_dominance': 4.7045, 'fully_diluted_market_cap': 257794266793.49, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 825, 'name': 'Tether USDt', 'symbol': 'USDT', 'slug': 'tether', 'num_market_pairs': 117647, 'date_added': '2015-02-25T00:00:00.000Z', 'tags': ['stablecoin', 'asset-backed-stablecoin', 'ethereum-ecosystem', 'waves-ecosystem', 'bitcoin-cash-ecosystem', 'heco-ecosystem', 'algorand-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'polygon-ecosystem', 'fantom-ecosystem', 'terra-ecosystem', 'tezos-ecosystem', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'celo-ecosystem', 'iotex-ecosystem', 'zilliqa-ecosystem', 'harmony-ecosystem', 'moonriver-ecosystem', 'cronos-ecosystem', 'injective-ecosystem', 'oasis-ecosystem', 'moonbeam-ecosystem', 'usd-stablecoin', 'xdc-ecosystem', 'everscale-ecosystem', 'velas-ecosystem', 'doge-chain-ecosystem', 'ethereum-pow-ecosystem', 'aptos-ecosystem', 'sui-ecosystem', 'optimism-ecosystem', 'canto-ecosystem', 'osmosis-ecosystem', 'zksync-era-ecosystem', 'pulsechain-ecosystem', 'sei-ecosystem', 'toncoin-ecosystem', 'fiat-stablecoin', 'viction-ecosystem', 'gnosis-chain-ecosystem', 'klaytn-ecosystem', 'okexchain-ecosystem', 'conflux-ecosystem', 'kcc-ecosystem', 'tron20-ecosystem', 'kardiachain-ecosystem', 'rsk-rbtc-ecosystem', 'telos-ecosystem', 'boba-network-ecosystem', 'fusion-network-ecosystem', 'hoo-smart-chain-ecosystem', 'secret-ecosystem', 'aurora-ecosystem', 'metis-andromeda-ecosystem', 'meter-ecosystem', 'fuse-ecosystem', 'syscoin-ecosystem', 'milkomeda-ecosystem', 'bitgert-ecosystem', 'astar-ecosystem', 'cube-network-ecosystem', 'thundercore-ecosystem', 'redlight-chain-ecosystem', 'core-ecosystem', 'polygon-zkevm-ecosystem', 'eos-evm-ecosystem', 'starknet-ecosystem', 'mantle-ecosystem', 'neon-evm-ecosystem', 'manta-pacific-ecosystem', 'scroll-ecosystem', 'x-layer-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 142489546124.8272, 'total_supply': 144566824343.61542, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0xdac17f958d2ee523a2206206994597c13d831ec7'}, 'infinite_supply': True, 'cmc_rank': 4, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 0.9999562299020588, 'volume_24h': 109499359055.53563, 'volume_change_24h': 53.1005, 'percent_change_1h': -0.00457145, 'percent_change_24h': -0.02313342, 'percent_change_7d': -0.02190098, 'percent_change_30d': 0.07371341, 'percent_change_60d': 0.1361927, 'percent_change_90d': -0.12085489, 'market_cap': 142483309343.4377, 'market_cap_dominance': 4.49, 'fully_diluted_market_cap': 144560496639.55, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 1839, 'name': 'BNB', 'symbol': 'BNB', 'slug': 'bnb', 'num_market_pairs': 2372, 'date_added': '2017-07-25T00:00:00.000Z', 'tags': ['marketplace', 'centralized-exchange', 'payments', 'smart-contracts', 'ethereum-ecosystem', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'bnb-chain-ecosystem', 'layer-1', 'alleged-sec-securities', 'celsius-bankruptcy-estate'], 'max_supply': None, 'circulating_supply': 142476711.79, 'total_supply': 142476711.79, 'infinite_supply': False, 'platform': None, 'cmc_rank': 5, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 655.1746971093634, 'volume_24h': 1959199815.0170271, 'volume_change_24h': 21.9566, 'percent_change_1h': 0.61922803, 'percent_change_24h': 0.43362094, 'percent_change_7d': -0.55083649, 'percent_change_30d': -4.44287767, 'percent_change_60d': -5.23331114, 'percent_change_90d': -1.24576238, 'market_cap': 93347136492.1513, 'market_cap_dominance': 2.9421, 'fully_diluted_market_cap': 93347136492.15, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 5426, 'name': 'Solana', 'symbol': 'SOL', 'slug': 'solana', 'num_market_pairs': 841, 'date_added': '2020-04-10T00:00:00.000Z', 'tags': ['pos', 'platform', 'solana-ecosystem', 'cms-holdings-portfolio', 'kenetic-capital-portfolio', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'okx-ventures-portfolio', 'layer-1', 'ftx-bankruptcy-estate', 'alleged-sec-securities', 'cmc-crypto-awards-2024', 'made-in-america'], 'max_supply': None, 'circulating_supply': 488731192.6180695, 'total_supply': 594683033.4978944, 'infinite_supply': True, 'platform': None, 'cmc_rank': 6, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 171.4613708842348, 'volume_24h': 4660819501.908409, 'volume_change_24h': 42.116, 'percent_change_1h': 0.55034387, 'percent_change_24h': -1.76721837, 'percent_change_7d': -13.1209376, 'percent_change_30d': -31.0193269, 'percent_change_60d': -10.21440571, 'percent_change_90d': -33.37448061, 'market_cap': 83798520280.18123, 'market_cap_dominance': 2.6418, 'fully_diluted_market_cap': 101965168165.14, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 3408, 'name': 'USDC', 'symbol': 'USDC', 'slug': 'usd-coin', 'num_market_pairs': 25894, 'date_added': '2018-10-08T00:00:00.000Z', 'tags': ['medium-of-exchange', 'stablecoin', 'asset-backed-stablecoin', 'ethereum-ecosystem', 'waves-ecosystem', 'bitcoin-cash-ecosystem', 'wanchain-ecosystem', 'coinbase-ventures-portfolio', 'algorand-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'hedera-hashgraph-ecosystem', 'polygon-ecosystem', 'terra-ecosystem', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'celo-ecosystem', 'iotex-ecosystem', 'harmony-ecosystem', 'moonriver-ecosystem', 'cronos-ecosystem', 'injective-ecosystem', 'oasis-ecosystem', 'moonbeam-ecosystem', 'usd-stablecoin', 'everscale-ecosystem', 'velas-ecosystem', 'doge-chain-ecosystem', 'ethereum-pow-ecosystem', 'aptos-ecosystem', 'sui-ecosystem', 'optimism-ecosystem', 'canto-ecosystem', 'osmosis-ecosystem', 'zksync-era-ecosystem', 'pulsechain-ecosystem', 'base-ecosystem', 'sei-ecosystem', 'multiversx-ecosystem', 'fiat-stablecoin', 'viction-ecosystem', 'gnosis-chain-ecosystem', 'okexchain-ecosystem', 'conflux-ecosystem', 'kcc-ecosystem', 'tron20-ecosystem', 'kardiachain-ecosystem', 'telos-ecosystem', 'ronin-ecosystem', 'boba-network-ecosystem', 'kava-ecosystem', 'secret-ecosystem', 'aurora-ecosystem', 'metis-andromeda-ecosystem', 'meter-ecosystem', 'fuse-ecosystem', 'elastos-ecosystem', 'syscoin-ecosystem', 'milkomeda-ecosystem', 'evmos-ecosystem', 'bitgert-ecosystem', 'astar-ecosystem', 'thundercore-ecosystem', 'tomb-chain-ecosystem', 'wemix-ecosystem', 'sx-network-ecosystem', 'godwoken-ecosystem', 'energi-ecosystem', 'core-ecosystem', 'polygon-zkevm-ecosystem', 'starknet-ecosystem', 'mantle-ecosystem', 'neon-evm-ecosystem', 'scroll-ecosystem', 'shido-network-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 57186437907.32239, 'total_supply': 57186437907.32239, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'}, 'infinite_supply': False, 'cmc_rank': 7, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 0.9999758346009517, 'volume_24h': 10782560037.903324, 'volume_change_24h': 46.586, 'percent_change_1h': -0.01085536, 'percent_change_24h': 0.00440557, 'percent_change_7d': -0.00952625, 'percent_change_30d': 0.00413669, 'percent_change_60d': -0.00241392, 'percent_change_90d': 0.00401234, 'market_cap': 57185055974.23021, 'market_cap_dominance': 1.8027, 'fully_diluted_market_cap': 57185055974.23, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 74, 'name': 'Dogecoin', 'symbol': 'DOGE', 'slug': 'dogecoin', 'num_market_pairs': 1168, 'date_added': '2013-12-15T00:00:00.000Z', 'tags': ['mineable', 'pow', 'scrypt', 'medium-of-exchange', 'memes', 'payments', 'doggone-doggerel', 'doge-chain-ecosystem', 'ftx-bankruptcy-estate', 'made-in-america'], 'max_supply': None, 'circulating_supply': 148147416383.70523, 'total_supply': 148147416383.70523, 'infinite_supply': True, 'platform': None, 'cmc_rank': 8, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 0.24282038978310544, 'volume_24h': 2099032106.115054, 'volume_change_24h': 89.8174, 'percent_change_1h': 0.32147156, 'percent_change_24h': -4.18038684, 'percent_change_7d': -12.81398791, 'percent_change_30d': -30.93675724, 'percent_change_60d': -24.76933829, 'percent_change_90d': -44.70760852, 'market_cap': 35973213391.65132, 'market_cap_dominance': 1.1338, 'fully_diluted_market_cap': 35973213391.65, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 2010, 'name': 'Cardano', 'symbol': 'ADA', 'slug': 'cardano', 'num_market_pairs': 1465, 'date_added': '2017-10-01T00:00:00.000Z', 'tags': ['dpos', 'pos', 'platform', 'research', 'smart-contracts', 'staking', 'cardano-ecosystem', 'cardano', 'layer-1', 'alleged-sec-securities', '2017-2018-alt-season', 'made-in-america'], 'max_supply': 45000000000, 'circulating_supply': 35204786637.28696, 'total_supply': 44994955922.926414, 'infinite_supply': False, 'platform': None, 'cmc_rank': 9, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 0.7693493892386892, 'volume_24h': 990669088.4027297, 'volume_change_24h': 48.3705, 'percent_change_1h': 0.35251761, 'percent_change_24h': -4.30431594, 'percent_change_7d': -4.82219831, 'percent_change_30d': -20.58453987, 'percent_change_60d': -15.73699525, 'percent_change_90d': -27.89897493, 'market_cap': 27084781097.675087, 'market_cap_dominance': 0.8538, 'fully_diluted_market_cap': 34620722515.74, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 1958, 'name': 'TRON', 'symbol': 'TRX', 'slug': 'tron', 'num_market_pairs': 1123, 'date_added': '2017-09-13T00:00:00.000Z', 'tags': ['media', 'payments', 'ethereum-ecosystem', 'tron-ecosystem', 'layer-1', 'dwf-labs-portfolio', 'alleged-sec-securities', '2017-2018-alt-season', 'tron20-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 86083864751.77873, 'total_supply': 86083885090.44815, 'infinite_supply': True, 'platform': None, 'cmc_rank': 10, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 0.23790289543994778, 'volume_24h': 644146594.8260555, 'volume_change_24h': 28.6828, 'percent_change_1h': -0.36970532, 'percent_change_24h': -4.81361156, 'percent_change_7d': 2.13411422, 'percent_change_30d': -4.10343635, 'percent_change_60d': -5.65296384, 'percent_change_90d': 10.5520786, 'market_cap': 20479600675.10902, 'market_cap_dominance': 0.6456, 'fully_diluted_market_cap': 20479605513.74, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 1975, 'name': 'Chainlink', 'symbol': 'LINK', 'slug': 'chainlink', 'num_market_pairs': 1932, 'date_added': '2017-09-20T00:00:00.000Z', 'tags': ['platform', 'defi', 'oracles', 'smart-contracts', 'ethereum-ecosystem', 'substrate', 'polkadot', 'heco-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'framework-ventures-portfolio', 'polygon-ecosystem', 'fantom-ecosystem', 'cardano-ecosystem', 'terra-ecosystem', 'web3', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'cardano', 'injective-ecosystem', 'bnb-chain-ecosystem', 'optimism-ecosystem', 'real-world-assets', 'celsius-bankruptcy-estate', 'gnosis-chain-ecosystem', 'sora-ecosystem', 'hoo-smart-chain-ecosystem', 'milkomeda-ecosystem', 'energi-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 638099970.4527867, 'total_supply': 1000000000, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0x514910771af9ca656af840dff83e8264ecf986ca'}, 'infinite_supply': False, 'cmc_rank': 11, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 17.56388813597504, 'volume_24h': 711132484.1151197, 'volume_change_24h': 93.0688, 'percent_change_1h': 0.40106165, 'percent_change_24h': -3.67718598, 'percent_change_7d': -10.20233621, 'percent_change_30d': -28.84069909, 'percent_change_60d': -27.34027977, 'percent_change_90d': -1.71670265, 'market_cap': 11207516500.601725, 'market_cap_dominance': 0.3533, 'fully_diluted_market_cap': 17563888135.98, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 5805, 'name': 'Avalanche', 'symbol': 'AVAX', 'slug': 'avalanche', 'num_market_pairs': 867, 'date_added': '2020-07-13T00:00:00.000Z', 'tags': ['defi', 'smart-contracts', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'avalanche-ecosystem', 'cms-holdings-portfolio', 'dragonfly-capital-portfolio', 'moonbeam-ecosystem', 'real-world-assets', 'layer-1', 'zksync-era-ecosystem', 'klaytn-ecosystem', 'made-in-america'], 'max_supply': 715748719, 'circulating_supply': 413958757.4465295, 'total_supply': 450628257.4465295, 'infinite_supply': False, 'platform': None, 'cmc_rank': 12, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 25.257441023697254, 'volume_24h': 659053329.4756662, 'volume_change_24h': 93.2003, 'percent_change_1h': 0.01015391, 'percent_change_24h': 1.01785283, 'percent_change_7d': -5.43069238, 'percent_change_30d': -29.41088494, 'percent_change_60d': -34.95691903, 'percent_change_90d': -40.74183285, 'market_cap': 10455538902.448715, 'market_cap_dominance': 0.3296, 'fully_diluted_market_cap': 18077981057.93, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 20947, 'name': 'Sui', 'symbol': 'SUI', 'slug': 'sui', 'num_market_pairs': 559, 'date_added': '2022-07-12T08:03:11.000Z', 'tags': ['binance-launchpool', 'coinbase-ventures-portfolio', 'binance-labs-portfolio', 'electric-capital-portfolio', 'a16z-portfolio', 'sui-ecosystem', 'layer-1', 'move-vm', 'cmc-crypto-yearbook-2024-2025', 'made-in-america'], 'max_supply': 10000000000, 'circulating_supply': 3089707194.508888, 'total_supply': 10000000000, 'infinite_supply': False, 'platform': None, 'cmc_rank': 13, 'self_reported_circulating_supply': 3089707194.508888, 'self_reported_market_cap': 10386478118.450756, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 3.361638325116985, 'volume_24h': 1239350873.1422524, 'volume_change_24h': 27.3218, 'percent_change_1h': 0.85694911, 'percent_change_24h': -5.01139315, 'percent_change_7d': -3.93846625, 'percent_change_30d': -23.65914

In [6]:
df = pd.json_normalize(data['data'])
df['timestamp']= pd.to_datetime('now')
df

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,timestamp
0,1,Bitcoin,BTC,bitcoin,11957,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.982749e+07,1.982749e+07,False,NaN,1,NaN,NaN,None,2025-02-22T05:15:00.000Z,96419.167582,4.938359e+10,60.2610,-0.003590,-1.900051,-1.100895,-5.608516,2.151511,-1.944783,1.911750e+12,60.2542,2.024803e+12,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
1,1027,Ethereum,ETH,ethereum,9946,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.205663e+08,1.205663e+08,True,NaN,2,NaN,NaN,None,2025-02-22T05:14:00.000Z,2678.237082,3.285710e+10,117.8005,-0.096498,-2.591738,-1.599968,-16.470500,-21.454320,-21.750458,3.229052e+11,10.1795,3.229052e+11,None,2025-02-22T05:14:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
2,52,XRP,XRP,xrp,1541,2013-08-04T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, xrp...",1.000000e+11,5.788781e+10,9.998642e+10,False,NaN,3,NaN,NaN,None,2025-02-22T05:15:00.000Z,2.577943,5.875942e+09,46.8163,0.147261,-2.928326,-7.935370,-17.595083,14.224170,75.454519,1.492314e+11,4.7045,2.577943e+11,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
3,825,Tether USDt,USDT,tether,117647,2015-02-25T00:00:00.000Z,"[stablecoin, asset-backed-stablecoin, ethereum...",NaN,1.424895e+11,1.445668e+11,True,NaN,4,NaN,NaN,None,2025-02-22T05:14:00.000Z,0.999956,1.094994e+11,53.1005,-0.004571,-0.023133,-0.021901,0.073713,0.136193,-0.120855,1.424833e+11,4.4900,1.445605e+11,None,2025-02-22T05:14:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,2025-02-22 10:46:04.471645
4,1839,BNB,BNB,bnb,2372,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.424767e+08,1.424767e+08,False,NaN,5,NaN,NaN,None,2025-02-22T05:15:00.000Z,655.174697,1.959200e+09,21.9566,0.619228,0.433621,-0.550836,-4.442878,-5.233311,-1.245762,9.334714e+10,2.9421,9.334714e+10,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
5,5426,Solana,SOL,solana,841,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,4.887312e+08,5.946830e+08,True,NaN,6,NaN,NaN,None,2025-02-22T05:15:00.000Z,171.461371,4.660820e+09,42.1160,0.550344,-1.767218,-13.120938,-31.019327,-10.214406,-33.374481,8.379852e+10,2.6418,1.019652e+11,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
6,3408,USDC,USDC,usd-coin,25894,2018-10-08T00:00:00.000Z,"[medium-of-exchange, stablecoin, asset-backed-...",NaN,5.718644e+10,5.718644e+10,False,NaN,7,NaN,NaN,None,2025-02-22T05:14:00.000Z,0.999976,1.078256e+10,46.5860,-0.010855,0.004406,-0.009526,0.004137,-0.002414,0.004012,5.718506e+10,1.8027,5.718506e+10,None,2025-02-22T05:14:00.000Z,1027.0,Ethereum,ETH,ethereum,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2025-02-22 10:46:04.471645
7,74,Dogecoin,DOGE,dogecoin,1168,2013-12-15T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange, me...",NaN,1.481474e+11,1.481474e+11,True,NaN,8,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.242820,2.099032e+09,89.8174,0.321472,-4.180387,-12.813988,-30.936757,-24.769338,-44.707609,3.597321e+10,1.1338,3.597321e+10,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
8,2010,Cardano,ADA,cardano,1465,2017-10-01T00:00:00.000Z,"[dpos, pos, platform, research, smart-contract...",4.500000e+10,3.520479e+10,4.499496e+10,False,NaN,9,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.769349,9.906691e+08,48.3705,0.352518,-4.304316,-4.822198,-20.584540,-15.736995,-27.898975,2.708478e+10,0.8538,3.462072e+10,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
9,1958,TRON,TRX,tron,1123,2017-09-13T00:00:00.000Z,"[media, payments, ethereum-ecosystem, tron-eco...",NaN,8.608386e+10,8.608389e+10,True,NaN,10,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.237903,6.441466e+08,28.6828,-0.369705,-4.813612,2.134114,-4.103436,-5.652964,10.552079,2.047960e+10,0.6456,2.047961e+10,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
10,1975,Chainlink,LINK,chainlink,1932,2017-09-20T00:00:00.000Z,"[platform, defi, oracles, smart-contracts, eth...",NaN,6.381000e+08,1.000000e+09,False,NaN,11,NaN,NaN,None,2025-02-22T05:15:00.000Z,17.563888,7.111325e+08,93.0688,0.401062,-3.677186,-10.202336,-28.840699,-27.340280,-1.716703,1.120752e+10,0.3533,1.756389e+10,None,2025-02-22T05:15:00.000Z,1027.0,Ethereum,ETH,ethereum,0x514910771af9ca656af840dff83e8264ecf986ca,2025-02-22 10:46:04.471645
11,5805,Avalanche,AVAX,avalanche,867,2020-07-13T00:00:00.000Z,"[defi, smart-contracts, three-arrows-capital-p...",7.157487e+08,4.139588e+08,4.506283e+08,False,NaN,12,NaN,NaN,None,2025-02-22T05:14:00.000Z,25.257441,6.590533e+08,93.2003,0.010154,1.017853,-5.430692,-29.410885,-34.956919,-40.741833,1.045554e+10,0.3296,1.807798e+10,None,2025-02-22T05:14:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
12,20947,Sui,SUI,sui,559,2022-07-12T08:03:11.000Z,"[binance-launchpool, coinbase-ventures-portfol...",1.000000e+10,3.089707e+09,1.000000e+10,False,NaN,13,3.089707e+09,1.038648e+10,None,2025-02-22T05:14:00.000Z,3.361638,1.239351e+09,27.3218,0.856949,-5.011393,-3.938466,-23.659148,-27.772241,-3.051920,1.038648e+10,0.3274,3.361638e+10,None,2025-02-22T05:14:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
13,512,Stellar,XLM,stellar,681,2014-08-05T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, dec...",5.000181e+10,3.065407e+10,5.000179e+10,False,NaN,14,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.329181,2.667584e+08,23.3882,0.348182,-2.981152,-8.656790,-21.751292,-12.138066,-44.811449,1.009074e+10,0.3181,1.645965e+10,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
14,2,Litecoin,LTC,litecoin,1319,2013-04-28T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange, he...",8.400000e+07,7.555847e+07,8.400000e+07,False,NaN,15,NaN,NaN,None,2025-02-22T05:15:00.000Z,129.466136,1.831633e+09,10.7706,0.941936,-3.788325,-0.535417,13.942284,21.229830,27.366436,9.782263e+09,0.3084,1.087516e+10,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645

In [7]:
def api_runner():
            url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
            parameters = {
              'start':'1',
              'limit':'1000',
              'convert':'USD'
            }
            headers = {
              'Accepts': 'application/json',
              'X-CMC_PRO_API_KEY': 'f4e28ecd-264a-4797-8bc5-3f0b7d51211e'
            }
            
            session = Session()
            session.headers.update(headers)
            
            try:
              response = session.get(url, params=parameters)
              data = json.loads(response.text)
              print(data)
            except (ConnectionError, Timeout, TooManyRedirects) as e:
              print(e)
            df2 = pd.json_normalize(data['data'])
            df2['timestamp']= pd.to_datetime('now')
            df = df2.append(df2)

In [10]:
import os
from time import time
from time import sleep

for i in range (333):
    api_runner()
    print('api runner successfully')
    sleep(60) # sleep for one minute (60seconds)
    exit()

{'status': {'timestamp': '2025-02-22T05:16:47.080Z', 'error_code': 0, 'error_message': None, 'elapsed': 25, 'credit_count': 5, 'notice': None, 'total_count': 10882}, 'data': [{'id': 1, 'name': 'Bitcoin', 'symbol': 'BTC', 'slug': 'bitcoin', 'num_market_pairs': 11957, 'date_added': '2010-07-13T00:00:00.000Z', 'tags': ['mineable', 'pow', 'sha-256', 'store-of-value', 'state-channel', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'binance-labs-portfolio', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'galaxy-digital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'bitcoin-ecosystem', 'ftx-bankruptcy-estate', '2017-2018-alt-season'], 'max_supply': 21000000, 'circulating_supply': 19827490, 'total_supply': 19827490, 'infinite_supply': False, 'platform': None, 'cmc_rank': 1, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 96419.16758201279, 'volume_24h': 49383585193.03519, 'volume_change_24h': 60.261, 'percent_change_1h': -0.0035905, 'percent_change_24h': -1.90005081, 'percent_change_7d': -1.10089495, 'percent_change_30d': -5.60851584, 'percent_change_60d': 2.1515109, 'percent_change_90d': -1.94478304, 'market_cap': 1911750081040.6826, 'market_cap_dominance': 60.2542, 'fully_diluted_market_cap': 2024802519222.27, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'num_market_pairs': 9946, 'date_added': '2015-08-07T00:00:00.000Z', 'tags': ['pos', 'smart-contracts', 'ethereum-ecosystem', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'heco-ecosystem', 'binance-labs-portfolio', 'avalanche-ecosystem', 'solana-ecosystem', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'hashkey-capital-portfolio', 'kenetic-capital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'tezos-ecosystem', 'near-protocol-ecosystem', 'velas-ecosystem', 'ethereum-pow-ecosystem', 'osmosis-ecosystem', 'layer-1', 'ftx-bankruptcy-estate', 'zksync-era-ecosystem', 'viction-ecosystem', 'klaytn-ecosystem', 'sora-ecosystem', 'rsk-rbtc-ecosystem', 'starknet-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 120566328.15075894, 'total_supply': 120566328.15075894, 'infinite_supply': True, 'platform': None, 'cmc_rank': 2, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 2678.2370816001753, 'volume_24h': 32857097693.649025, 'volume_change_24h': 117.8005, 'percent_change_1h': -0.09649823, 'percent_change_24h': -2.59173822, 'percent_change_7d': -1.59996845, 'percent_change_30d': -16.4705, 'percent_change_60d': -21.45431962, 'percent_change_90d': -21.75045818, 'market_cap': 322905210845.7377, 'market_cap_dominance': 10.1795, 'fully_diluted_market_cap': 322905210845.74, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 52, 'name': 'XRP', 'symbol': 'XRP', 'slug': 'xrp', 'num_market_pairs': 1541, 'date_added': '2013-08-04T00:00:00.000Z', 'tags': ['medium-of-exchange', 'enterprise-solutions', 'xrp-ecosystem', 'arrington-xrp-capital-portfolio', 'galaxy-digital-portfolio', 'a16z-portfolio', 'pantera-capital-portfolio', 'ftx-bankruptcy-estate', '2017-2018-alt-season', 'klaytn-ecosystem', 'made-in-america'], 'max_supply': 100000000000, 'circulating_supply': 57887806032, 'total_supply': 99986418374, 'infinite_supply': False, 'platform': None, 'cmc_rank': 3, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 2.5779426679349013, 'volume_24h': 5875942030.6162815, 'volume_change_24h': 46.8163, 'percent_change_1h': 0.14726143, 'percent_change_24h': -2.92832621, 'percent_change_7d': -7.93537041, 'percent_change_30d': -17.59508321, 'percent_change_60d': 14.22417032, 'percent_change_90d': 75.45451876, 'market_cap': 149231445123.03217, 'market_cap_dominance': 4.7045, 'fully_diluted_market_cap': 257794266793.49, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 825, 'name': 'Tether USDt', 'symbol': 'USDT', 'slug': 'tether', 'num_market_pairs': 117647, 'date_added': '2015-02-25T00:00:00.000Z', 'tags': ['stablecoin', 'asset-backed-stablecoin', 'ethereum-ecosystem', 'waves-ecosystem', 'bitcoin-cash-ecosystem', 'heco-ecosystem', 'algorand-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'polygon-ecosystem', 'fantom-ecosystem', 'terra-ecosystem', 'tezos-ecosystem', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'celo-ecosystem', 'iotex-ecosystem', 'zilliqa-ecosystem', 'harmony-ecosystem', 'moonriver-ecosystem', 'cronos-ecosystem', 'injective-ecosystem', 'oasis-ecosystem', 'moonbeam-ecosystem', 'usd-stablecoin', 'xdc-ecosystem', 'everscale-ecosystem', 'velas-ecosystem', 'doge-chain-ecosystem', 'ethereum-pow-ecosystem', 'aptos-ecosystem', 'sui-ecosystem', 'optimism-ecosystem', 'canto-ecosystem', 'osmosis-ecosystem', 'zksync-era-ecosystem', 'pulsechain-ecosystem', 'sei-ecosystem', 'toncoin-ecosystem', 'fiat-stablecoin', 'viction-ecosystem', 'gnosis-chain-ecosystem', 'klaytn-ecosystem', 'okexchain-ecosystem', 'conflux-ecosystem', 'kcc-ecosystem', 'tron20-ecosystem', 'kardiachain-ecosystem', 'rsk-rbtc-ecosystem', 'telos-ecosystem', 'boba-network-ecosystem', 'fusion-network-ecosystem', 'hoo-smart-chain-ecosystem', 'secret-ecosystem', 'aurora-ecosystem', 'metis-andromeda-ecosystem', 'meter-ecosystem', 'fuse-ecosystem', 'syscoin-ecosystem', 'milkomeda-ecosystem', 'bitgert-ecosystem', 'astar-ecosystem', 'cube-network-ecosystem', 'thundercore-ecosystem', 'redlight-chain-ecosystem', 'core-ecosystem', 'polygon-zkevm-ecosystem', 'eos-evm-ecosystem', 'starknet-ecosystem', 'mantle-ecosystem', 'neon-evm-ecosystem', 'manta-pacific-ecosystem', 'scroll-ecosystem', 'x-layer-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 142489546124.8272, 'total_supply': 144566824343.61542, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0xdac17f958d2ee523a2206206994597c13d831ec7'}, 'infinite_supply': True, 'cmc_rank': 4, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 0.9999562299020588, 'volume_24h': 109499359055.53563, 'volume_change_24h': 53.1005, 'percent_change_1h': -0.00457145, 'percent_change_24h': -0.02313342, 'percent_change_7d': -0.02190098, 'percent_change_30d': 0.07371341, 'percent_change_60d': 0.1361927, 'percent_change_90d': -0.12085489, 'market_cap': 142483309343.4377, 'market_cap_dominance': 4.49, 'fully_diluted_market_cap': 144560496639.55, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 1839, 'name': 'BNB', 'symbol': 'BNB', 'slug': 'bnb', 'num_market_pairs': 2372, 'date_added': '2017-07-25T00:00:00.000Z', 'tags': ['marketplace', 'centralized-exchange', 'payments', 'smart-contracts', 'ethereum-ecosystem', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'bnb-chain-ecosystem', 'layer-1', 'alleged-sec-securities', 'celsius-bankruptcy-estate'], 'max_supply': None, 'circulating_supply': 142476711.79, 'total_supply': 142476711.79, 'infinite_supply': False, 'platform': None, 'cmc_rank': 5, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 655.1746971093634, 'volume_24h': 1959199815.0170271, 'volume_change_24h': 21.9566, 'percent_change_1h': 0.61922803, 'percent_change_24h': 0.43362094, 'percent_change_7d': -0.55083649, 'percent_change_30d': -4.44287767, 'percent_change_60d': -5.23331114, 'percent_change_90d': -1.24576238, 'market_cap': 93347136492.1513, 'market_cap_dominance': 2.9421, 'fully_diluted_market_cap': 93347136492.15, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 5426, 'name': 'Solana', 'symbol': 'SOL', 'slug': 'solana', 'num_market_pairs': 841, 'date_added': '2020-04-10T00:00:00.000Z', 'tags': ['pos', 'platform', 'solana-ecosystem', 'cms-holdings-portfolio', 'kenetic-capital-portfolio', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'okx-ventures-portfolio', 'layer-1', 'ftx-bankruptcy-estate', 'alleged-sec-securities', 'cmc-crypto-awards-2024', 'made-in-america'], 'max_supply': None, 'circulating_supply': 488731192.6180695, 'total_supply': 594683033.4978944, 'infinite_supply': True, 'platform': None, 'cmc_rank': 6, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 171.4613708842348, 'volume_24h': 4660819501.908409, 'volume_change_24h': 42.116, 'percent_change_1h': 0.55034387, 'percent_change_24h': -1.76721837, 'percent_change_7d': -13.1209376, 'percent_change_30d': -31.0193269, 'percent_change_60d': -10.21440571, 'percent_change_90d': -33.37448061, 'market_cap': 83798520280.18123, 'market_cap_dominance': 2.6418, 'fully_diluted_market_cap': 101965168165.14, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 3408, 'name': 'USDC', 'symbol': 'USDC', 'slug': 'usd-coin', 'num_market_pairs': 25894, 'date_added': '2018-10-08T00:00:00.000Z', 'tags': ['medium-of-exchange', 'stablecoin', 'asset-backed-stablecoin', 'ethereum-ecosystem', 'waves-ecosystem', 'bitcoin-cash-ecosystem', 'wanchain-ecosystem', 'coinbase-ventures-portfolio', 'algorand-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'hedera-hashgraph-ecosystem', 'polygon-ecosystem', 'terra-ecosystem', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'celo-ecosystem', 'iotex-ecosystem', 'harmony-ecosystem', 'moonriver-ecosystem', 'cronos-ecosystem', 'injective-ecosystem', 'oasis-ecosystem', 'moonbeam-ecosystem', 'usd-stablecoin', 'everscale-ecosystem', 'velas-ecosystem', 'doge-chain-ecosystem', 'ethereum-pow-ecosystem', 'aptos-ecosystem', 'sui-ecosystem', 'optimism-ecosystem', 'canto-ecosystem', 'osmosis-ecosystem', 'zksync-era-ecosystem', 'pulsechain-ecosystem', 'base-ecosystem', 'sei-ecosystem', 'multiversx-ecosystem', 'fiat-stablecoin', 'viction-ecosystem', 'gnosis-chain-ecosystem', 'okexchain-ecosystem', 'conflux-ecosystem', 'kcc-ecosystem', 'tron20-ecosystem', 'kardiachain-ecosystem', 'telos-ecosystem', 'ronin-ecosystem', 'boba-network-ecosystem', 'kava-ecosystem', 'secret-ecosystem', 'aurora-ecosystem', 'metis-andromeda-ecosystem', 'meter-ecosystem', 'fuse-ecosystem', 'elastos-ecosystem', 'syscoin-ecosystem', 'milkomeda-ecosystem', 'evmos-ecosystem', 'bitgert-ecosystem', 'astar-ecosystem', 'thundercore-ecosystem', 'tomb-chain-ecosystem', 'wemix-ecosystem', 'sx-network-ecosystem', 'godwoken-ecosystem', 'energi-ecosystem', 'core-ecosystem', 'polygon-zkevm-ecosystem', 'starknet-ecosystem', 'mantle-ecosystem', 'neon-evm-ecosystem', 'scroll-ecosystem', 'shido-network-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 57186437907.32239, 'total_supply': 57186437907.32239, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'}, 'infinite_supply': False, 'cmc_rank': 7, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 0.9999758346009517, 'volume_24h': 10782560037.903324, 'volume_change_24h': 46.586, 'percent_change_1h': -0.01085536, 'percent_change_24h': 0.00440557, 'percent_change_7d': -0.00952625, 'percent_change_30d': 0.00413669, 'percent_change_60d': -0.00241392, 'percent_change_90d': 0.00401234, 'market_cap': 57185055974.23021, 'market_cap_dominance': 1.8027, 'fully_diluted_market_cap': 57185055974.23, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 74, 'name': 'Dogecoin', 'symbol': 'DOGE', 'slug': 'dogecoin', 'num_market_pairs': 1168, 'date_added': '2013-12-15T00:00:00.000Z', 'tags': ['mineable', 'pow', 'scrypt', 'medium-of-exchange', 'memes', 'payments', 'doggone-doggerel', 'doge-chain-ecosystem', 'ftx-bankruptcy-estate', 'made-in-america'], 'max_supply': None, 'circulating_supply': 148147416383.70523, 'total_supply': 148147416383.70523, 'infinite_supply': True, 'platform': None, 'cmc_rank': 8, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 0.24282038978310544, 'volume_24h': 2099032106.115054, 'volume_change_24h': 89.8174, 'percent_change_1h': 0.32147156, 'percent_change_24h': -4.18038684, 'percent_change_7d': -12.81398791, 'percent_change_30d': -30.93675724, 'percent_change_60d': -24.76933829, 'percent_change_90d': -44.70760852, 'market_cap': 35973213391.65132, 'market_cap_dominance': 1.1338, 'fully_diluted_market_cap': 35973213391.65, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 2010, 'name': 'Cardano', 'symbol': 'ADA', 'slug': 'cardano', 'num_market_pairs': 1465, 'date_added': '2017-10-01T00:00:00.000Z', 'tags': ['dpos', 'pos', 'platform', 'research', 'smart-contracts', 'staking', 'cardano-ecosystem', 'cardano', 'layer-1', 'alleged-sec-securities', '2017-2018-alt-season', 'made-in-america'], 'max_supply': 45000000000, 'circulating_supply': 35204786637.28696, 'total_supply': 44994955922.926414, 'infinite_supply': False, 'platform': None, 'cmc_rank': 9, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 0.7693493892386892, 'volume_24h': 990669088.4027297, 'volume_change_24h': 48.3705, 'percent_change_1h': 0.35251761, 'percent_change_24h': -4.30431594, 'percent_change_7d': -4.82219831, 'percent_change_30d': -20.58453987, 'percent_change_60d': -15.73699525, 'percent_change_90d': -27.89897493, 'market_cap': 27084781097.675087, 'market_cap_dominance': 0.8538, 'fully_diluted_market_cap': 34620722515.74, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 1958, 'name': 'TRON', 'symbol': 'TRX', 'slug': 'tron', 'num_market_pairs': 1123, 'date_added': '2017-09-13T00:00:00.000Z', 'tags': ['media', 'payments', 'ethereum-ecosystem', 'tron-ecosystem', 'layer-1', 'dwf-labs-portfolio', 'alleged-sec-securities', '2017-2018-alt-season', 'tron20-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 86083864751.77873, 'total_supply': 86083885090.44815, 'infinite_supply': True, 'platform': None, 'cmc_rank': 10, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 0.23790289543994778, 'volume_24h': 644146594.8260555, 'volume_change_24h': 28.6828, 'percent_change_1h': -0.36970532, 'percent_change_24h': -4.81361156, 'percent_change_7d': 2.13411422, 'percent_change_30d': -4.10343635, 'percent_change_60d': -5.65296384, 'percent_change_90d': 10.5520786, 'market_cap': 20479600675.10902, 'market_cap_dominance': 0.6456, 'fully_diluted_market_cap': 20479605513.74, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 1975, 'name': 'Chainlink', 'symbol': 'LINK', 'slug': 'chainlink', 'num_market_pairs': 1932, 'date_added': '2017-09-20T00:00:00.000Z', 'tags': ['platform', 'defi', 'oracles', 'smart-contracts', 'ethereum-ecosystem', 'substrate', 'polkadot', 'heco-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'framework-ventures-portfolio', 'polygon-ecosystem', 'fantom-ecosystem', 'cardano-ecosystem', 'terra-ecosystem', 'web3', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'cardano', 'injective-ecosystem', 'bnb-chain-ecosystem', 'optimism-ecosystem', 'real-world-assets', 'celsius-bankruptcy-estate', 'gnosis-chain-ecosystem', 'sora-ecosystem', 'hoo-smart-chain-ecosystem', 'milkomeda-ecosystem', 'energi-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 638099970.4527867, 'total_supply': 1000000000, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0x514910771af9ca656af840dff83e8264ecf986ca'}, 'infinite_supply': False, 'cmc_rank': 11, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:15:00.000Z', 'quote': {'USD': {'price': 17.56388813597504, 'volume_24h': 711132484.1151197, 'volume_change_24h': 93.0688, 'percent_change_1h': 0.40106165, 'percent_change_24h': -3.67718598, 'percent_change_7d': -10.20233621, 'percent_change_30d': -28.84069909, 'percent_change_60d': -27.34027977, 'percent_change_90d': -1.71670265, 'market_cap': 11207516500.601725, 'market_cap_dominance': 0.3533, 'fully_diluted_market_cap': 17563888135.98, 'tvl': None, 'last_updated': '2025-02-22T05:15:00.000Z'}}}, {'id': 5805, 'name': 'Avalanche', 'symbol': 'AVAX', 'slug': 'avalanche', 'num_market_pairs': 867, 'date_added': '2020-07-13T00:00:00.000Z', 'tags': ['defi', 'smart-contracts', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'avalanche-ecosystem', 'cms-holdings-portfolio', 'dragonfly-capital-portfolio', 'moonbeam-ecosystem', 'real-world-assets', 'layer-1', 'zksync-era-ecosystem', 'klaytn-ecosystem', 'made-in-america'], 'max_supply': 715748719, 'circulating_supply': 413958757.4465295, 'total_supply': 450628257.4465295, 'infinite_supply': False, 'platform': None, 'cmc_rank': 12, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 25.257441023697254, 'volume_24h': 659053329.4756662, 'volume_change_24h': 93.2003, 'percent_change_1h': 0.01015391, 'percent_change_24h': 1.01785283, 'percent_change_7d': -5.43069238, 'percent_change_30d': -29.41088494, 'percent_change_60d': -34.95691903, 'percent_change_90d': -40.74183285, 'market_cap': 10455538902.448715, 'market_cap_dominance': 0.3296, 'fully_diluted_market_cap': 18077981057.93, 'tvl': None, 'last_updated': '2025-02-22T05:14:00.000Z'}}}, {'id': 20947, 'name': 'Sui', 'symbol': 'SUI', 'slug': 'sui', 'num_market_pairs': 559, 'date_added': '2022-07-12T08:03:11.000Z', 'tags': ['binance-launchpool', 'coinbase-ventures-portfolio', 'binance-labs-portfolio', 'electric-capital-portfolio', 'a16z-portfolio', 'sui-ecosystem', 'layer-1', 'move-vm', 'cmc-crypto-yearbook-2024-2025', 'made-in-america'], 'max_supply': 10000000000, 'circulating_supply': 3089707194.508888, 'total_supply': 10000000000, 'infinite_supply': False, 'platform': None, 'cmc_rank': 13, 'self_reported_circulating_supply': 3089707194.508888, 'self_reported_market_cap': 10386478118.450756, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:14:00.000Z', 'quote': {'USD': {'price': 3.361638325116985, 'volume_24h': 1239350873.1422524, 'volume_change_24h': 27.3218, 'percent_change_1h': 0.85694911, 'percent_change_24h': -5.01139315, 'percent_change_7d': -3.93846625, 'percent_change_30d': -23.65914

AttributeError: 'DataFrame' object has no attribute 'append'

In [14]:
#chatgpt code

In [15]:
def api_runner():

            global  df # alex having error not mine
            url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
            parameters = {
              'start':'1',
              'limit':'1000',
              'convert':'USD'
            }
            headers = {
              'Accepts': 'application/json',
              'X-CMC_PRO_API_KEY': 'f4e28ecd-264a-4797-8bc5-3f0b7d51211e'
            }
            
            session = Session()
            session.headers.update(headers)
            
            try:
              response = session.get(url, params=parameters)
              data = json.loads(response.text)
              print(data)
            except (ConnectionError, Timeout, TooManyRedirects) as e:
              print(e)
            df2 = pd.json_normalize(data['data'])
            df2['timestamp']= pd.to_datetime('now')
            df  #  = pd.concat([df2,df2],ignore_index = True)(no need to type this)
            #vary apis append data to a csv
          #  if not os.path.isfile(r'jo b location h file ka jha pe all apis h vo typekro  ')
             #       df.to_csv(r'copy above',header = 'column_names')
           # else :df.to_csv(r'same above',mode = 'a' ,headers =  False )## a means append

In [ ]:
import os
from time import time
from time import sleep

for i in range (333):
    api_runner()
    print('api runner successfully')
    sleep(60) # sleep for one minute (60seconds)
    exit()

{'status': {'timestamp': '2025-02-22T05:09:31.119Z', 'error_code': 0, 'error_message': None, 'elapsed': 27, 'credit_count': 5, 'notice': None, 'total_count': 10882}, 'data': [{'id': 1, 'name': 'Bitcoin', 'symbol': 'BTC', 'slug': 'bitcoin', 'num_market_pairs': 11957, 'date_added': '2010-07-13T00:00:00.000Z', 'tags': ['mineable', 'pow', 'sha-256', 'store-of-value', 'state-channel', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'binance-labs-portfolio', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'galaxy-digital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'bitcoin-ecosystem', 'ftx-bankruptcy-estate', '2017-2018-alt-season'], 'max_supply': 21000000, 'circulating_supply': 19827490, 'total_supply': 19827490, 'infinite_supply': False, 'platform': None, 'cmc_rank': 1, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:06:00.000Z', 'quote': {'USD': {'price': 96408.77898146893, 'volume_24h': 49348023811.98393, 'volume_change_24h': 60.1638, 'percent_change_1h': 0.09705553, 'percent_change_24h': -1.8711696, 'percent_change_7d': -1.1729227, 'percent_change_30d': -5.48308572, 'percent_change_60d': 2.30434339, 'percent_change_90d': -1.91790182, 'market_cap': 1911544101167.2854, 'market_cap_dominance': 60.4394, 'fully_diluted_market_cap': 2024584358610.85, 'tvl': None, 'last_updated': '2025-02-22T05:06:00.000Z'}}}, {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'num_market_pairs': 9946, 'date_added': '2015-08-07T00:00:00.000Z', 'tags': ['pos', 'smart-contracts', 'ethereum-ecosystem', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'heco-ecosystem', 'binance-labs-portfolio', 'avalanche-ecosystem', 'solana-ecosystem', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'hashkey-capital-portfolio', 'kenetic-capital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'tezos-ecosystem', 'near-protocol-ecosystem', 'velas-ecosystem', 'ethereum-pow-ecosystem', 'osmosis-ecosystem', 'layer-1', 'ftx-bankruptcy-estate', 'zksync-era-ecosystem', 'viction-ecosystem', 'klaytn-ecosystem', 'sora-ecosystem', 'rsk-rbtc-ecosystem', 'starknet-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 120566328.15075894, 'total_supply': 120566328.15075894, 'infinite_supply': True, 'platform': None, 'cmc_rank': 2, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:06:00.000Z', 'quote': {'USD': {'price': 2681.744542408931, 'volume_24h': 32827813207.088123, 'volume_change_24h': 132.5221, 'percent_change_1h': 0.18914955, 'percent_change_24h': -2.48614447, 'percent_change_7d': -1.48980171, 'percent_change_30d': -16.24306543, 'percent_change_60d': -21.29432061, 'percent_change_90d': -21.50348721, 'market_cap': 323328092516.58203, 'market_cap_dominance': 10.1867, 'fully_diluted_market_cap': 323328092516.58, 'tvl': None, 'last_updated': '2025-02-22T05:06:00.000Z'}}}, {'id': 52, 'name': 'XRP', 'symbol': 'XRP', 'slug': 'xrp', 'num_market_pairs': 1541, 'date_added': '2013-08-04T00:00:00.000Z', 'tags': ['medium-of-exchange', 'enterprise-solutions', 'xrp-ecosystem', 'arrington-xrp-capital-portfolio', 'galaxy-digital-portfolio', 'a16z-portfolio', 'pantera-capital-portfolio', 'ftx-bankruptcy-estate', '2017-2018-alt-season', 'klaytn-ecosystem', 'made-in-america'], 'max_supply': 100000000000, 'circulating_supply': 57887806032, 'total_supply': 99986418374, 'infinite_supply': False, 'platform': None, 'cmc_rank': 3, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:07:00.000Z', 'quote': {'USD': {'price': 2.58121558223793, 'volume_24h': 5881872910.305929, 'volume_change_24h': 47.1137, 'percent_change_1h': 0.33779654, 'percent_change_24h': -2.87725675, 'percent_change_7d': -7.67989687, 'percent_change_30d': -17.33747091, 'percent_change_60d': 14.28890229, 'percent_change_90d': 76.49565855, 'market_cap': 149420906951.36523, 'market_cap_dominance': 4.7082, 'fully_diluted_market_cap': 258121558223.79, 'tvl': None, 'last_updated': '2025-02-22T05:07:00.000Z'}}}, {'id': 825, 'name': 'Tether USDt', 'symbol': 'USDT', 'slug': 'tether', 'num_market_pairs': 117647, 'date_added': '2015-02-25T00:00:00.000Z', 'tags': ['stablecoin', 'asset-backed-stablecoin', 'ethereum-ecosystem', 'waves-ecosystem', 'bitcoin-cash-ecosystem', 'heco-ecosystem', 'algorand-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'polygon-ecosystem', 'fantom-ecosystem', 'terra-ecosystem', 'tezos-ecosystem', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'celo-ecosystem', 'iotex-ecosystem', 'zilliqa-ecosystem', 'harmony-ecosystem', 'moonriver-ecosystem', 'cronos-ecosystem', 'injective-ecosystem', 'oasis-ecosystem', 'moonbeam-ecosystem', 'usd-stablecoin', 'xdc-ecosystem', 'everscale-ecosystem', 'velas-ecosystem', 'doge-chain-ecosystem', 'ethereum-pow-ecosystem', 'aptos-ecosystem', 'sui-ecosystem', 'optimism-ecosystem', 'canto-ecosystem', 'osmosis-ecosystem', 'zksync-era-ecosystem', 'pulsechain-ecosystem', 'sei-ecosystem', 'toncoin-ecosystem', 'fiat-stablecoin', 'viction-ecosystem', 'gnosis-chain-ecosystem', 'klaytn-ecosystem', 'okexchain-ecosystem', 'conflux-ecosystem', 'kcc-ecosystem', 'tron20-ecosystem', 'kardiachain-ecosystem', 'rsk-rbtc-ecosystem', 'telos-ecosystem', 'boba-network-ecosystem', 'fusion-network-ecosystem', 'hoo-smart-chain-ecosystem', 'secret-ecosystem', 'aurora-ecosystem', 'metis-andromeda-ecosystem', 'meter-ecosystem', 'fuse-ecosystem', 'syscoin-ecosystem', 'milkomeda-ecosystem', 'bitgert-ecosystem', 'astar-ecosystem', 'cube-network-ecosystem', 'thundercore-ecosystem', 'redlight-chain-ecosystem', 'core-ecosystem', 'polygon-zkevm-ecosystem', 'eos-evm-ecosystem', 'starknet-ecosystem', 'mantle-ecosystem', 'neon-evm-ecosystem', 'manta-pacific-ecosystem', 'scroll-ecosystem', 'x-layer-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 142489546124.8272, 'total_supply': 144566824343.61542, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0xdac17f958d2ee523a2206206994597c13d831ec7'}, 'infinite_supply': True, 'cmc_rank': 4, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:06:00.000Z', 'quote': {'USD': {'price': 0.9999408909167007, 'volume_24h': 109664027954.59921, 'volume_change_24h': 55.6043, 'percent_change_1h': -0.00081892, 'percent_change_24h': -0.02818451, 'percent_change_7d': -0.00420177, 'percent_change_30d': 0.07711023, 'percent_change_60d': 0.13734025, 'percent_change_90d': -0.12398667, 'market_cap': 142481123698.37604, 'market_cap_dominance': 4.505, 'fully_diluted_market_cap': 144558279131.15, 'tvl': None, 'last_updated': '2025-02-22T05:06:00.000Z'}}}, {'id': 1839, 'name': 'BNB', 'symbol': 'BNB', 'slug': 'bnb', 'num_market_pairs': 2372, 'date_added': '2017-07-25T00:00:00.000Z', 'tags': ['marketplace', 'centralized-exchange', 'payments', 'smart-contracts', 'ethereum-ecosystem', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'bnb-chain-ecosystem', 'layer-1', 'alleged-sec-securities', 'celsius-bankruptcy-estate'], 'max_supply': None, 'circulating_supply': 142476712.84, 'total_supply': 142476712.84, 'infinite_supply': False, 'platform': None, 'cmc_rank': 5, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:07:00.000Z', 'quote': {'USD': {'price': 654.9662801326045, 'volume_24h': 1957500983.6698854, 'volume_change_24h': 21.7019, 'percent_change_1h': 0.64547084, 'percent_change_24h': 0.37361297, 'percent_change_7d': -0.46348624, 'percent_change_30d': -4.44778949, 'percent_change_60d': -5.26600181, 'percent_change_90d': -0.80127562, 'market_cap': 93317442614.33609, 'market_cap_dominance': 2.9505, 'fully_diluted_market_cap': 93317442614.34, 'tvl': None, 'last_updated': '2025-02-22T05:07:00.000Z'}}}, {'id': 5426, 'name': 'Solana', 'symbol': 'SOL', 'slug': 'solana', 'num_market_pairs': 841, 'date_added': '2020-04-10T00:00:00.000Z', 'tags': ['pos', 'platform', 'solana-ecosystem', 'cms-holdings-portfolio', 'kenetic-capital-portfolio', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'okx-ventures-portfolio', 'layer-1', 'ftx-bankruptcy-estate', 'alleged-sec-securities', 'cmc-crypto-awards-2024', 'made-in-america'], 'max_supply': None, 'circulating_supply': 488611413.9585436, 'total_supply': 594529951.5885122, 'infinite_supply': True, 'platform': None, 'cmc_rank': 6, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:06:00.000Z', 'quote': {'USD': {'price': 171.57983934903692, 'volume_24h': 4671767551.463973, 'volume_change_24h': 42.9039, 'percent_change_1h': 0.71008294, 'percent_change_24h': -1.53986259, 'percent_change_7d': -13.17436056, 'percent_change_30d': -30.84228629, 'percent_change_60d': -9.98576395, 'percent_change_90d': -33.29039073, 'market_cap': 83835867911.11269, 'market_cap_dominance': 2.6414, 'fully_diluted_market_cap': 102009353581.75, 'tvl': None, 'last_updated': '2025-02-22T05:06:00.000Z'}}}, {'id': 3408, 'name': 'USDC', 'symbol': 'USDC', 'slug': 'usd-coin', 'num_market_pairs': 25894, 'date_added': '2018-10-08T00:00:00.000Z', 'tags': ['medium-of-exchange', 'stablecoin', 'asset-backed-stablecoin', 'ethereum-ecosystem', 'waves-ecosystem', 'bitcoin-cash-ecosystem', 'wanchain-ecosystem', 'coinbase-ventures-portfolio', 'algorand-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'hedera-hashgraph-ecosystem', 'polygon-ecosystem', 'terra-ecosystem', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'celo-ecosystem', 'iotex-ecosystem', 'harmony-ecosystem', 'moonriver-ecosystem', 'cronos-ecosystem', 'injective-ecosystem', 'oasis-ecosystem', 'moonbeam-ecosystem', 'usd-stablecoin', 'everscale-ecosystem', 'velas-ecosystem', 'doge-chain-ecosystem', 'ethereum-pow-ecosystem', 'aptos-ecosystem', 'sui-ecosystem', 'optimism-ecosystem', 'canto-ecosystem', 'osmosis-ecosystem', 'zksync-era-ecosystem', 'pulsechain-ecosystem', 'base-ecosystem', 'sei-ecosystem', 'multiversx-ecosystem', 'fiat-stablecoin', 'viction-ecosystem', 'gnosis-chain-ecosystem', 'okexchain-ecosystem', 'conflux-ecosystem', 'kcc-ecosystem', 'tron20-ecosystem', 'kardiachain-ecosystem', 'telos-ecosystem', 'ronin-ecosystem', 'boba-network-ecosystem', 'kava-ecosystem', 'secret-ecosystem', 'aurora-ecosystem', 'metis-andromeda-ecosystem', 'meter-ecosystem', 'fuse-ecosystem', 'elastos-ecosystem', 'syscoin-ecosystem', 'milkomeda-ecosystem', 'evmos-ecosystem', 'bitgert-ecosystem', 'astar-ecosystem', 'thundercore-ecosystem', 'tomb-chain-ecosystem', 'wemix-ecosystem', 'sx-network-ecosystem', 'godwoken-ecosystem', 'energi-ecosystem', 'core-ecosystem', 'polygon-zkevm-ecosystem', 'starknet-ecosystem', 'mantle-ecosystem', 'neon-evm-ecosystem', 'scroll-ecosystem', 'shido-network-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 57193620635.54928, 'total_supply': 57193620635.54928, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'}, 'infinite_supply': False, 'cmc_rank': 7, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:06:00.000Z', 'quote': {'USD': {'price': 0.999988750802728, 'volume_24h': 10858373115.587362, 'volume_change_24h': 46.9459, 'percent_change_1h': -0.00216142, 'percent_change_24h': 0.00679751, 'percent_change_7d': 0.00993284, 'percent_change_30d': 0.01351792, 'percent_change_60d': -0.002346, 'percent_change_90d': 0.00928758, 'market_cap': 57192977253.22805, 'market_cap_dominance': 1.8019, 'fully_diluted_market_cap': 57192977253.23, 'tvl': None, 'last_updated': '2025-02-22T05:06:00.000Z'}}}, {'id': 74, 'name': 'Dogecoin', 'symbol': 'DOGE', 'slug': 'dogecoin', 'num_market_pairs': 1168, 'date_added': '2013-12-15T00:00:00.000Z', 'tags': ['mineable', 'pow', 'scrypt', 'medium-of-exchange', 'memes', 'payments', 'doggone-doggerel', 'doge-chain-ecosystem', 'ftx-bankruptcy-estate', 'made-in-america'], 'max_supply': None, 'circulating_supply': 148147106383.70523, 'total_supply': 148147106383.70523, 'infinite_supply': True, 'platform': None, 'cmc_rank': 8, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:06:00.000Z', 'quote': {'USD': {'price': 0.2429208993087351, 'volume_24h': 2098001945.2316203, 'volume_change_24h': 89.8255, 'percent_change_1h': 0.44896688, 'percent_change_24h': -4.21529883, 'percent_change_7d': -12.79151777, 'percent_change_30d': -30.84137063, 'percent_change_60d': -24.66123986, 'percent_change_90d': -44.52934708, 'market_cap': 35988028312.71652, 'market_cap_dominance': 1.1379, 'fully_diluted_market_cap': 35988028312.72, 'tvl': None, 'last_updated': '2025-02-22T05:06:00.000Z'}}}, {'id': 2010, 'name': 'Cardano', 'symbol': 'ADA', 'slug': 'cardano', 'num_market_pairs': 1465, 'date_added': '2017-10-01T00:00:00.000Z', 'tags': ['dpos', 'pos', 'platform', 'research', 'smart-contracts', 'staking', 'cardano-ecosystem', 'cardano', 'layer-1', 'alleged-sec-securities', '2017-2018-alt-season', 'made-in-america'], 'max_supply': 45000000000, 'circulating_supply': 35204786637.28696, 'total_supply': 44994955922.926414, 'infinite_supply': False, 'platform': None, 'cmc_rank': 9, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:07:00.000Z', 'quote': {'USD': {'price': 0.7702799842437067, 'volume_24h': 990640698.031485, 'volume_change_24h': 48.3785, 'percent_change_1h': 0.66028501, 'percent_change_24h': -4.23794192, 'percent_change_7d': -4.78113264, 'percent_change_30d': -20.26509487, 'percent_change_60d': -15.57707324, 'percent_change_90d': -27.49382065, 'market_cap': 27117542496.272453, 'market_cap_dominance': 0.8545, 'fully_diluted_market_cap': 34662599290.97, 'tvl': None, 'last_updated': '2025-02-22T05:07:00.000Z'}}}, {'id': 1958, 'name': 'TRON', 'symbol': 'TRX', 'slug': 'tron', 'num_market_pairs': 1123, 'date_added': '2017-09-13T00:00:00.000Z', 'tags': ['media', 'payments', 'ethereum-ecosystem', 'tron-ecosystem', 'layer-1', 'dwf-labs-portfolio', 'alleged-sec-securities', '2017-2018-alt-season', 'tron20-ecosystem', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 86083864751.77873, 'total_supply': 86083861282.34682, 'infinite_supply': True, 'platform': None, 'cmc_rank': 10, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:07:00.000Z', 'quote': {'USD': {'price': 0.23795906991733248, 'volume_24h': 643726498.2675194, 'volume_change_24h': 28.3424, 'percent_change_1h': -0.25050525, 'percent_change_24h': -4.77556269, 'percent_change_7d': 2.22353776, 'percent_change_30d': -4.05300647, 'percent_change_60d': -5.5761485, 'percent_change_90d': 10.70564746, 'market_cap': 20484436391.22271, 'market_cap_dominance': 0.6455, 'fully_diluted_market_cap': 20484435565.64, 'tvl': None, 'last_updated': '2025-02-22T05:07:00.000Z'}}}, {'id': 1975, 'name': 'Chainlink', 'symbol': 'LINK', 'slug': 'chainlink', 'num_market_pairs': 1932, 'date_added': '2017-09-20T00:00:00.000Z', 'tags': ['platform', 'defi', 'oracles', 'smart-contracts', 'ethereum-ecosystem', 'substrate', 'polkadot', 'heco-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'framework-ventures-portfolio', 'polygon-ecosystem', 'fantom-ecosystem', 'cardano-ecosystem', 'terra-ecosystem', 'web3', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'cardano', 'injective-ecosystem', 'bnb-chain-ecosystem', 'optimism-ecosystem', 'real-world-assets', 'celsius-bankruptcy-estate', 'gnosis-chain-ecosystem', 'sora-ecosystem', 'hoo-smart-chain-ecosystem', 'milkomeda-ecosystem', 'energi-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio'], 'max_supply': None, 'circulating_supply': 638099970.4527867, 'total_supply': 1000000000, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0x514910771af9ca656af840dff83e8264ecf986ca'}, 'infinite_supply': False, 'cmc_rank': 11, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:07:00.000Z', 'quote': {'USD': {'price': 17.578709683911207, 'volume_24h': 710805366.1293783, 'volume_change_24h': 92.2607, 'percent_change_1h': 0.64797982, 'percent_change_24h': -3.63960585, 'percent_change_7d': -10.10053791, 'percent_change_30d': -28.56788344, 'percent_change_60d': -27.40555224, 'percent_change_90d': -1.20580003, 'market_cap': 11216974129.901855, 'market_cap_dominance': 0.3534, 'fully_diluted_market_cap': 17578709683.91, 'tvl': None, 'last_updated': '2025-02-22T05:07:00.000Z'}}}, {'id': 5805, 'name': 'Avalanche', 'symbol': 'AVAX', 'slug': 'avalanche', 'num_market_pairs': 867, 'date_added': '2020-07-13T00:00:00.000Z', 'tags': ['defi', 'smart-contracts', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'avalanche-ecosystem', 'cms-holdings-portfolio', 'dragonfly-capital-portfolio', 'moonbeam-ecosystem', 'real-world-assets', 'layer-1', 'zksync-era-ecosystem', 'klaytn-ecosystem', 'made-in-america'], 'max_supply': 715748719, 'circulating_supply': 413958719.3468748, 'total_supply': 450628219.3468748, 'infinite_supply': False, 'platform': None, 'cmc_rank': 12, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:06:00.000Z', 'quote': {'USD': {'price': 25.271780845514545, 'volume_24h': 657750667.3507333, 'volume_change_24h': 92.7057, 'percent_change_1h': 0.89452104, 'percent_change_24h': 0.72031428, 'percent_change_7d': -5.33054583, 'percent_change_30d': -29.22866156, 'percent_change_60d': -34.87872199, 'percent_change_90d': -40.75560308, 'market_cap': 10461474034.424082, 'market_cap_dominance': 0.3296, 'fully_diluted_market_cap': 18088244767.03, 'tvl': None, 'last_updated': '2025-02-22T05:06:00.000Z'}}}, {'id': 20947, 'name': 'Sui', 'symbol': 'SUI', 'slug': 'sui', 'num_market_pairs': 559, 'date_added': '2022-07-12T08:03:11.000Z', 'tags': ['binance-launchpool', 'coinbase-ventures-portfolio', 'binance-labs-portfolio', 'electric-capital-portfolio', 'a16z-portfolio', 'sui-ecosystem', 'layer-1', 'move-vm', 'cmc-crypto-yearbook-2024-2025', 'made-in-america'], 'max_supply': 10000000000, 'circulating_supply': 3089707194.508888, 'total_supply': 10000000000, 'infinite_supply': False, 'platform': None, 'cmc_rank': 13, 'self_reported_circulating_supply': 3089707194.508888, 'self_reported_market_cap': 10376257668.995941, 'tvl_ratio': None, 'last_updated': '2025-02-22T05:06:00.000Z', 'quote': {'USD': {'price': 3.358330422842951, 'volume_24h': 1238158597.368592, 'volume_change_24h': 27.1486, 'percent_change_1h': 1.05627924, 'percent_change_24h': -5.42963448, 'percent_change_7d': -4.16146867, 'percent_change_30d': -23.62

In [7]:
df = pd.json_normalize(data['data'])
df['timestamp']= pd.to_datetime('now')
df

NameError: name 'pd' is not defined

In [8]:
# 22:33 tk hogya h

In [194]:
df

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Index: []

#pd.set_option('display.float_format', (lambda x: '%.5f' % x))

# yha pe alex mai error aara h op
#tion error(arey float spelling glt tha bss)

In [13]:
pd.set_option('display.float_format', (lambda x: '%.5f' % x))

In [11]:
print(type(data))  # Should be <class 'dict'>

<class 'dict'>

In [15]:
df

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,timestamp
0,1,Bitcoin,BTC,bitcoin,11957,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",21000000.00000,19827490.00000,19827490.00000,False,NaN,1,NaN,NaN,None,2025-02-22T05:15:00.000Z,96419.16758,49383585193.03519,60.26100,-0.00359,-1.90005,-1.10089,-5.60852,2.15151,-1.94478,1911750081040.68262,60.25420,2024802519222.27002,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
1,1027,Ethereum,ETH,ethereum,9946,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,120566328.15076,120566328.15076,True,NaN,2,NaN,NaN,None,2025-02-22T05:14:00.000Z,2678.23708,32857097693.64902,117.80050,-0.09650,-2.59174,-1.59997,-16.47050,-21.45432,-21.75046,322905210845.73767,10.17950,322905210845.73999,None,2025-02-22T05:14:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
2,52,XRP,XRP,xrp,1541,2013-08-04T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, xrp...",100000000000.00000,57887806032.00000,99986418374.00000,False,NaN,3,NaN,NaN,None,2025-02-22T05:15:00.000Z,2.57794,5875942030.61628,46.81630,0.14726,-2.92833,-7.93537,-17.59508,14.22417,75.45452,149231445123.03217,4.70450,257794266793.48999,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
3,825,Tether USDt,USDT,tether,117647,2015-02-25T00:00:00.000Z,"[stablecoin, asset-backed-stablecoin, ethereum...",NaN,142489546124.82721,144566824343.61542,True,NaN,4,NaN,NaN,None,2025-02-22T05:14:00.000Z,0.99996,109499359055.53563,53.10050,-0.00457,-0.02313,-0.02190,0.07371,0.13619,-0.12085,142483309343.43771,4.49000,144560496639.54999,None,2025-02-22T05:14:00.000Z,1027.00000,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,2025-02-22 10:46:04.471645
4,1839,BNB,BNB,bnb,2372,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,142476711.79000,142476711.79000,False,NaN,5,NaN,NaN,None,2025-02-22T05:15:00.000Z,655.17470,1959199815.01703,21.95660,0.61923,0.43362,-0.55084,-4.44288,-5.23331,-1.24576,93347136492.15131,2.94210,93347136492.14999,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
5,5426,Solana,SOL,solana,841,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,488731192.61807,594683033.49789,True,NaN,6,NaN,NaN,None,2025-02-22T05:15:00.000Z,171.46137,4660819501.90841,42.11600,0.55034,-1.76722,-13.12094,-31.01933,-10.21441,-33.37448,83798520280.18123,2.64180,101965168165.14000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
6,3408,USDC,USDC,usd-coin,25894,2018-10-08T00:00:00.000Z,"[medium-of-exchange, stablecoin, asset-backed-...",NaN,57186437907.32239,57186437907.32239,False,NaN,7,NaN,NaN,None,2025-02-22T05:14:00.000Z,0.99998,10782560037.90332,46.58600,-0.01086,0.00441,-0.00953,0.00414,-0.00241,0.00401,57185055974.23021,1.80270,57185055974.23000,None,2025-02-22T05:14:00.000Z,1027.00000,Ethereum,ETH,ethereum,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2025-02-22 10:46:04.471645
7,74,Dogecoin,DOGE,dogecoin,1168,2013-12-15T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange, me...",NaN,148147416383.70523,148147416383.70523,True,NaN,8,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.24282,2099032106.11505,89.81740,0.32147,-4.18039,-12.81399,-30.93676,-24.76934,-44.70761,35973213391.65132,1.13380,35973213391.65000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
8,2010,Cardano,ADA,cardano,1465,2017-10-01T00:00:00.000Z,"[dpos, pos, platform, research, smart-contract...",45000000000.00000,35204786637.28696,44994955922.92641,False,NaN,9,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.76935,990669088.40273,48.37050,0.35252,-4.30432,-4.82220,-20.58454,-15.73700,-27.89897,27084781097.67509,0.85380,34620722515.74000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
9,1958,TRON,TRX,tron,1123,2017-09-13T00:00:00.000Z,"[media, payments, ethereum-ecosystem, tron-eco...",NaN,86083864751.77873,86083885090.44815,True,NaN,10,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.23790,644146594.82606,28.68280,-0.36971,-4.81361,2.13411,-4.10344,-5.65296,10.55208,20479600675.10902,0.64560,20479605513.74000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
10,1975,Chainlink,LINK,chainlink,1932,2017-09-20T00:00:00.000Z,"[platform, defi, oracles, smart-contracts, eth...",NaN,638099970.45279,1000000000.00000,False,NaN,11,NaN,NaN,None,2025-02-22T05:15:00.000Z,17.56389,711132484.11512,93.06880,0.40106,-3.67719,-10.20234,-28.84070,-27.34028,-1.71670,11207516500.60172,0.35330,17563888135.98000,None,2025-02-22T05:15:00.000Z,1027.00000,Ethereum,ETH,ethereum,0x514910771af9ca656af840dff83e8264ecf986ca,2025-02-22 10:46:04.471645
11,5805,Avalanche,AVAX,avalanche,867,2020-07-13T00:00:00.000Z,"[defi, smart-contracts, three-arrows-capital-p...",715748719.00000,413958757.44653,450628257.44653,False,NaN,12,NaN,NaN,None,2025-02-22T05:14:00.000Z,25.25744,659053329.47567,93.20030,0.01015,1.01785,-5.43069,-29.41088,-34.95692,-40.74183,10455538902.44872,0.32960,18077981057.93000,None,2025-02-22T05:14:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
12,20947,Sui,SUI,sui,559,2022-07-12T08:03:11.000Z,"[binance-launchpool, coinbase-ventures-portfol...",10000000000.00000,3089707194.50889,10000000000.00000,False,NaN,13,3089707194.50889,10386478118.45076,None,2025-02-22T05:14:00.000Z,3.36164,1239350873.14225,27.32180,0.85695,-5.01139,-3.93847,-23.65915,-27.77224,-3.05192,10386478118.45076,0.32740,33616383251.17000,None,2025-02-22T05:14:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
13,512,Stellar,XLM,stellar,681,2014-08-05T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, dec...",50001806812.00000,30654073855.57794,50001786894.45013,False,NaN,14,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.32918,266758426.83975,23.38820,0.34818,-2.98115,-8.65679,-21.75129,-12.13807,-44.81145,10090742994.87713,0.31810,16459651796.90000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
14,2,Litecoin,LTC,litecoin,1319,2013-04-28T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange, he...",84000000.00000,75558468.30409,84000000.00000,False,NaN,15,NaN,NaN,None,2025-02-22T05:15:00.000Z,129.46614,1831633334.61028,10.77060,0.94194,-3.78833,-0.53542,13.94228,21.22983,27.36644,9782262901.55203,0.30840,10875155388.58000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645

In [16]:
pd.set_option('display.float_format', (lambda x: '%.5f' % x))

In [18]:
df #(finally workded bc)

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,timestamp
0,1,Bitcoin,BTC,bitcoin,11957,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",21000000.00000,19827490.00000,19827490.00000,False,NaN,1,NaN,NaN,None,2025-02-22T05:15:00.000Z,96419.16758,49383585193.03519,60.26100,-0.00359,-1.90005,-1.10089,-5.60852,2.15151,-1.94478,1911750081040.68262,60.25420,2024802519222.27002,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
1,1027,Ethereum,ETH,ethereum,9946,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,120566328.15076,120566328.15076,True,NaN,2,NaN,NaN,None,2025-02-22T05:14:00.000Z,2678.23708,32857097693.64902,117.80050,-0.09650,-2.59174,-1.59997,-16.47050,-21.45432,-21.75046,322905210845.73767,10.17950,322905210845.73999,None,2025-02-22T05:14:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
2,52,XRP,XRP,xrp,1541,2013-08-04T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, xrp...",100000000000.00000,57887806032.00000,99986418374.00000,False,NaN,3,NaN,NaN,None,2025-02-22T05:15:00.000Z,2.57794,5875942030.61628,46.81630,0.14726,-2.92833,-7.93537,-17.59508,14.22417,75.45452,149231445123.03217,4.70450,257794266793.48999,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
3,825,Tether USDt,USDT,tether,117647,2015-02-25T00:00:00.000Z,"[stablecoin, asset-backed-stablecoin, ethereum...",NaN,142489546124.82721,144566824343.61542,True,NaN,4,NaN,NaN,None,2025-02-22T05:14:00.000Z,0.99996,109499359055.53563,53.10050,-0.00457,-0.02313,-0.02190,0.07371,0.13619,-0.12085,142483309343.43771,4.49000,144560496639.54999,None,2025-02-22T05:14:00.000Z,1027.00000,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,2025-02-22 10:46:04.471645
4,1839,BNB,BNB,bnb,2372,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,142476711.79000,142476711.79000,False,NaN,5,NaN,NaN,None,2025-02-22T05:15:00.000Z,655.17470,1959199815.01703,21.95660,0.61923,0.43362,-0.55084,-4.44288,-5.23331,-1.24576,93347136492.15131,2.94210,93347136492.14999,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
5,5426,Solana,SOL,solana,841,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,488731192.61807,594683033.49789,True,NaN,6,NaN,NaN,None,2025-02-22T05:15:00.000Z,171.46137,4660819501.90841,42.11600,0.55034,-1.76722,-13.12094,-31.01933,-10.21441,-33.37448,83798520280.18123,2.64180,101965168165.14000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
6,3408,USDC,USDC,usd-coin,25894,2018-10-08T00:00:00.000Z,"[medium-of-exchange, stablecoin, asset-backed-...",NaN,57186437907.32239,57186437907.32239,False,NaN,7,NaN,NaN,None,2025-02-22T05:14:00.000Z,0.99998,10782560037.90332,46.58600,-0.01086,0.00441,-0.00953,0.00414,-0.00241,0.00401,57185055974.23021,1.80270,57185055974.23000,None,2025-02-22T05:14:00.000Z,1027.00000,Ethereum,ETH,ethereum,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2025-02-22 10:46:04.471645
7,74,Dogecoin,DOGE,dogecoin,1168,2013-12-15T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange, me...",NaN,148147416383.70523,148147416383.70523,True,NaN,8,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.24282,2099032106.11505,89.81740,0.32147,-4.18039,-12.81399,-30.93676,-24.76934,-44.70761,35973213391.65132,1.13380,35973213391.65000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
8,2010,Cardano,ADA,cardano,1465,2017-10-01T00:00:00.000Z,"[dpos, pos, platform, research, smart-contract...",45000000000.00000,35204786637.28696,44994955922.92641,False,NaN,9,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.76935,990669088.40273,48.37050,0.35252,-4.30432,-4.82220,-20.58454,-15.73700,-27.89897,27084781097.67509,0.85380,34620722515.74000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
9,1958,TRON,TRX,tron,1123,2017-09-13T00:00:00.000Z,"[media, payments, ethereum-ecosystem, tron-eco...",NaN,86083864751.77873,86083885090.44815,True,NaN,10,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.23790,644146594.82606,28.68280,-0.36971,-4.81361,2.13411,-4.10344,-5.65296,10.55208,20479600675.10902,0.64560,20479605513.74000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
10,1975,Chainlink,LINK,chainlink,1932,2017-09-20T00:00:00.000Z,"[platform, defi, oracles, smart-contracts, eth...",NaN,638099970.45279,1000000000.00000,False,NaN,11,NaN,NaN,None,2025-02-22T05:15:00.000Z,17.56389,711132484.11512,93.06880,0.40106,-3.67719,-10.20234,-28.84070,-27.34028,-1.71670,11207516500.60172,0.35330,17563888135.98000,None,2025-02-22T05:15:00.000Z,1027.00000,Ethereum,ETH,ethereum,0x514910771af9ca656af840dff83e8264ecf986ca,2025-02-22 10:46:04.471645
11,5805,Avalanche,AVAX,avalanche,867,2020-07-13T00:00:00.000Z,"[defi, smart-contracts, three-arrows-capital-p...",715748719.00000,413958757.44653,450628257.44653,False,NaN,12,NaN,NaN,None,2025-02-22T05:14:00.000Z,25.25744,659053329.47567,93.20030,0.01015,1.01785,-5.43069,-29.41088,-34.95692,-40.74183,10455538902.44872,0.32960,18077981057.93000,None,2025-02-22T05:14:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
12,20947,Sui,SUI,sui,559,2022-07-12T08:03:11.000Z,"[binance-launchpool, coinbase-ventures-portfol...",10000000000.00000,3089707194.50889,10000000000.00000,False,NaN,13,3089707194.50889,10386478118.45076,None,2025-02-22T05:14:00.000Z,3.36164,1239350873.14225,27.32180,0.85695,-5.01139,-3.93847,-23.65915,-27.77224,-3.05192,10386478118.45076,0.32740,33616383251.17000,None,2025-02-22T05:14:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
13,512,Stellar,XLM,stellar,681,2014-08-05T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, dec...",50001806812.00000,30654073855.57794,50001786894.45013,False,NaN,14,NaN,NaN,None,2025-02-22T05:15:00.000Z,0.32918,266758426.83975,23.38820,0.34818,-2.98115,-8.65679,-21.75129,-12.13807,-44.81145,10090742994.87713,0.31810,16459651796.90000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645
14,2,Litecoin,LTC,litecoin,1319,2013-04-28T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange, he...",84000000.00000,75558468.30409,84000000.00000,False,NaN,15,NaN,NaN,None,2025-02-22T05:15:00.000Z,129.46614,1831633334.61028,10.77060,0.94194,-3.78833,-0.53542,13.94228,21.22983,27.36644,9782262901.55203,0.30840,10875155388.58000,None,2025-02-22T05:15:00.000Z,NaN,NaN,NaN,NaN,NaN,2025-02-22 10:46:04.471645

In [19]:
# scroll down krne k lia

In [140]:
#import pandas as pd
#pd.set_option('display.max_columns', None)  # Show all columns properly
#pd.set_option('display.width', 1000)  # Set a wider display width
#pd.set_option('display.colheader_justify', 'center')  # Align headers

In [141]:
#df

In [143]:
#df3 = df.groupby('name', sort = False)[['quote.USD.percent_change_1','quote.USD.volume_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d	','quote.USD.percent_change_60d	','quote.USD.percent_change_90d	']].mean()
#df3

In [37]:
#chatgpt code

In [38]:
print(df.columns.tolist())  # See the actual column names

['id', 'name', 'symbol', 'slug', 'num_market_pairs', 'date_added', 'tags', 'max_supply', 'circulating_supply', 'total_supply', 'infinite_supply', 'platform', 'cmc_rank', 'self_reported_circulating_supply', 'self_reported_market_cap', 'tvl_ratio', 'last_updated', 'quote.USD.price', 'quote.USD.volume_24h', 'quote.USD.volume_change_24h', 'quote.USD.percent_change_1h', 'quote.USD.percent_change_24h', 'quote.USD.percent_change_7d', 'quote.USD.percent_change_30d', 'quote.USD.percent_change_60d', 'quote.USD.percent_change_90d', 'quote.USD.market_cap', 'quote.USD.market_cap_dominance', 'quote.USD.fully_diluted_market_cap', 'quote.USD.tvl', 'quote.USD.last_updated', 'platform.id', 'platform.name', 'platform.symbol', 'platform.slug', 'platform.token_address', 'timestamp']

In [39]:
#df.columns = df.columns.str.strip()  # Removes spaces and hidden characters

In [146]:
#df3 = df.groupby('name', sort=False)[[
#    'quote.USD.percent_change_1h', 
#    'quote.USD.volume_change_24h', 
 W#   'quote.USD.percent_change_7d', 
  #  'quote.USD.percent_change_30d', 
  #  'quote.USD.percent_change_60d', 
   # 'quote.USD.percent_change_90d'
#]].mean()
Wdf

IndentationError: unexpected indent (595247770.py, line 4)

In [42]:
df.columns = df.columns.str.strip()  # Removes hidden spaces or tab characters
print(df.columns.tolist())  # Check correct column names

['id', 'name', 'symbol', 'slug', 'num_market_pairs', 'date_added', 'tags', 'max_supply', 'circulating_supply', 'total_supply', 'infinite_supply', 'platform', 'cmc_rank', 'self_reported_circulating_supply', 'self_reported_market_cap', 'tvl_ratio', 'last_updated', 'quote.USD.price', 'quote.USD.volume_24h', 'quote.USD.volume_change_24h', 'quote.USD.percent_change_1h', 'quote.USD.percent_change_24h', 'quote.USD.percent_change_7d', 'quote.USD.percent_change_30d', 'quote.USD.percent_change_60d', 'quote.USD.percent_change_90d', 'quote.USD.market_cap', 'quote.USD.market_cap_dominance', 'quote.USD.fully_diluted_market_cap', 'quote.USD.tvl', 'quote.USD.last_updated', 'platform.id', 'platform.name', 'platform.symbol', 'platform.slug', 'platform.token_address', 'timestamp']

In [147]:
#df3 = df.groupby('name', sort=False)[[
    'quote.USD.percent_change_1h', 
    'quote.USD.percent_change_24h', 
    'quote.USD.percent_change_7d', 
    'quote.USD.percent_change_30d', 
    'quote.USD.percent_change_60d', 
    'quote.USD.percent_change_90d'
]].mean()

IndentationError: unexpected indent (28416027.py, line 2)

In [148]:
#import pandas as pd

#pd.set_option('display.float_format', '{:.4f}'.format)  # Format decimals
#df3 = df3.reset_index()  # Ensure 'name' is a column, not an index
#print(df3)

In [149]:
#from IPython.display import display
#display(df3)
# like alex video (yarr but numbers thode alag h )

In [151]:
#df4 = df3.stack()
#df4

In [152]:
#df5 = df4.to_frame(name = 'values')
#df5

In [68]:
#df5 = df4.to_frame(name='values')  # Convert Series to DataFrame
#df5 = df5.reset_index()  # Reset index to get 'name' and 'metric' columns
#df5.columns = ['name', 'metric', 'values']  # Rename columns properly

# Display the DataFrame
#import pandas as pd
#pd.set_option('display.float_format', '{:.4f}'.format)  # Format decimals
#display(df5)

In [153]:
#df6 = df5.set_index(df5['name'])
#df6

In [154]:
#df5.count()  # alex mai yha 90 values h and int64 in dtype

In [156]:
#index = pd.Index(range(105)) #alex mai 90 h
#df6 = df5.set_index(index)
#df6

In [73]:
# reset the index

In [157]:
#index = pd.Index(range(105)) #alex mai 90 h
#df6 = df5.reset_index()
#df6

In [158]:

import pandas as pd

# Reset index
df6 = df5.reset_index()

# Print column names to debug
print("Columns after reset_index():", df6.columns)

# Drop the 'index' column if it exists
if 'index' in df6.columns:
    df6 = df6.drop(columns=['index'])

# Rename columns based on actual column names
expected_columns = ['name', 'metric', 'values']

if len(df6.columns) == 4:  # If an extra column exists
    df6.columns = ['index', 'name', 'metric', 'values']
    df6 = df6.drop(columns=['index'])  # Remove unnecessary index column
elif len(df6.columns) == 3:
    df6.columns = expected_columns
else:
    print("Unexpected column structure:", df6.columns)

# Convert 'name' column to string (only if it exists)
if 'name' in df6.columns:
    df6['name'] = df6['name'].astype(str)

# Ensure 'name' appears only once per group
if 'name' in df6.columns:
    df6.loc[df6.duplicated(subset=['name']), 'name'] = ''

# Display the cleaned DataFrame
display(df6)

Columns after reset_index(): Index(['level_0', 'level_1', 'values'], dtype='object')

    name             metric               values
0     0                           name      Bitcoin
1          quote.USD.percent_change_1h      -0.0036
2         quote.USD.percent_change_24h      -1.9001
3          quote.USD.percent_change_7d      -1.1009
4         quote.USD.percent_change_30d      -5.6085
5         quote.USD.percent_change_60d       2.1515
6         quote.USD.percent_change_90d      -1.9448
7     1                           name     Ethereum
8          quote.USD.percent_change_1h      -0.0965
9         quote.USD.percent_change_24h      -2.5917
10         quote.USD.percent_change_7d      -1.6000
11        quote.USD.percent_change_30d     -16.4705
12        quote.USD.percent_change_60d     -21.4543
13        quote.USD.percent_change_90d     -21.7505
14    2                           name          XRP
15         quote.USD.percent_change_1h       0.1473
16        quote.USD.percent_change_24h      -2.9283
17         quote.USD.percent_change_7d      -7.9354
18        quote.USD.percent_change_30d     -17.5951
19        quote.USD.percent_change_60d      14.2242
20        quote.USD.percent_change_90d      75.4545
21    3                           name  Tether USDt
22         quote.USD.percent_change_1h      -0.0046
23        quote.USD.percent_change_24h      -0.0231
24         quote.USD.percent_change_7d      -0.0219
25        quote.USD.percent_change_30d       0.0737
26        quote.USD.percent_change_60d       0.1362
27        quote.USD.percent_change_90d      -0.1209
28    4                           name          BNB
29         quote.USD.percent_change_1h       0.6192
30        quote.USD.percent_change_24h       0.4336
31         quote.USD.percent_change_7d      -0.5508
32        quote.USD.percent_change_30d      -4.4429
33        quote.USD.percent_change_60d      -5.2333
34        quote.USD.percent_change_90d      -1.2458
35    5                           name       Solana
36         quote.USD.percent_change_1h       0.5503
37        quote.USD.percent_change_24h      -1.7672
38         quote.USD.percent_change_7d     -13.1209
39        quote.USD.percent_change_30d     -31.0193
40        quote.USD.percent_change_60d     -10.2144
41        quote.USD.percent_change_90d     -33.3745
42    6                           name         USDC
43         quote.USD.percent_change_1h      -0.0109
44        quote.USD.percent_change_24h       0.0044
45         quote.USD.percent_change_7d      -0.0095
46        quote.USD.percent_change_30d       0.0041
47        quote.USD.percent_change_60d      -0.0024
48        quote.USD.percent_change_90d       0.0040
49    7                           name     Dogecoin
50         quote.USD.percent_change_1h       0.3215
51        quote.USD.percent_change_24h      -4.1804
52         quote.USD.percent_change_7d     -12.8140
53        quote.USD.percent_change_30d     -30.9368
54        quote.USD.percent_change_60d     -24.7693
55        quote.USD.percent_change_90d     -44.7076
56    8                           name      Cardano
57         quote.USD.percent_change_1h       0.3525
58        quote.USD.percent_change_24h      -4.3043
59         quote.USD.percent_change_7d      -4.8222
60        quote.USD.percent_change_30d     -20.5845
61        quote.USD.percent_change_60d     -15.7370
62        quote.USD.percent_change_90d     -27.8990
63    9                           name         TRON
64         quote.USD.percent_change_1h      -0.3697
65        quote.USD.percent_change_24h      -4.8136
66         quote.USD.percent_change_7d       2.1341
67        quote.USD.percent_change_30d      -4.1034
68        quote.USD.percent_change_60d      -5.6530
69        quote.USD.percent_change_90d      10.5521
70   10                           name    Chainlink
71         quote.USD.percent_change_1h       0.4011
72        quote.USD.percent_change_24h      -3.6772
73         quote.USD.percent_change_7d     -10.2023
74        quote.USD.percent_change_30d     -28.8407
75        quote.USD.percent_change_60d     -27.3403
76        quote.USD.percent_change_90d      -1.7167
77   11                           name    Avalanche
78         quote.USD.percent_change_1h       0.0102
79        quote.USD.percent_change_24h       1.0179
80         quote.USD.percent_change_7d      -5.4307
81        quote.USD.percent_change_30d     -29.4109
82        quote.USD.percent_change_60d     -34.9569
83        quote.USD.percent_change_90d     -40.7418
84   12                           name          Sui
85         quote.USD.percent_change_1h       0.8569
86        quote.USD.percent_change_24h      -5.0114
87         quote.USD.percent_change_7d      -3.9385
88        quote.USD.percent_change_30d     -23.6591
89        quote.USD.percent_change_60d     -27.7722
90        quote.USD.percent_change_90d      -3.0519
91   13                           name      Stellar
92         quote.USD.percent_change_1h       0.3482
93        quote.USD.percent_change_24h      -2.9812
94         quote.USD.percent_change_7d      -8.6568
95        quote.USD.percent_change_30d     -21.7513
96        quote.USD.percent_change_60d     -12.1381
97        quote.USD.percent_change_90d     -44.8114
98   14                           name     Litecoin
99         quote.USD.percent_change_1h       0.9419
100       quote.USD.percent_change_24h      -3.7883
101        quote.USD.percent_change_7d      -0.5354
102       quote.USD.percent_change_30d      13.9423
103       quote.USD.percent_change_60d      21.2298
104       quote.USD.percent_change_90d      27.3664

In [90]:
print(df6.columns)

Index(['name', 'metric', 'values'], dtype='object')

In [92]:
#alex ka jaise nhi aara h

In [159]:
#df7 = df6.rename(columns={'level_1': 'percent_change'})
#df7

In [160]:

#df7_pivot = df7.pivot_table(index='name', columns='metric', values='values', aggfunc='first')
#df7_pivot

In [161]:
#df7_melted = df7.melt(id_vars=['name'], var_name='percent_change', value_name='values')
#df7_melted

In [162]:
#df7_melted

In [120]:
# viusualise (bhai uper wala bhot try krlia sayad koi aur end se probelm h sayad )

In [163]:
#import seaborn as sns
#import matplotlib.pyplot as plt

In [164]:
#sns.catplot(x='name', y='values', hue='name', data=df7, kind='point')

In [123]:
# chatgpt

In [165]:
#print(df7.columns)

In [166]:
#print(df7.dtypes)

In [167]:
#df7['name'] = df7['name'].astype(str)

In [169]:
#print(df7.isnull().sum())
#Wprint(df7['values'].dtype)
#@df7['values'] = pd.to_numeric(df7['values'], errors='coerce')
#sns.catplot(x='name', y='values', hue='name', data=df7, kind='point')


#( values and name ka to plot hogya h alex mai values and percentage(after changing the name of 'level_1') ko kia h )

In [171]:
# alex redo bc (probem df3 se shuru)

In [172]:
df3 = df.groupby('name', sort=False)[['quote.USD.percent_change_1h','quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d']].mean()
df3

KeyError: 'name'

In [173]:
#chatgpt

In [175]:
print(df.columns)
df['name'] = 'default_name'  # Replace with actual values if possible

Index(['values'], dtype='object')

In [176]:
print(df.head())  # Check the first few rows

                                values       name
0 name                          Bitcoin  default_name
  quote.USD.percent_change_1h   -0.0036  default_name
  quote.USD.percent_change_24h  -1.9001  default_name
  quote.USD.percent_change_7d   -1.1009  default_name
  quote.USD.percent_change_30d  -5.6085  default_name

In [177]:
df = df.reset_index()
df = df.T  # Transpose the DataFrame
df.columns = df.iloc[0]  # Set the first row as column names
df = df[1:].reset_index(drop=True)  # Remove the first row and reset index

In [178]:
print(df.columns)

Index([ 0,  0,  0,  0,  0,  0,  0,  1,  1,  1,
       ...
       13, 13, 13, 14, 14, 14, 14, 14, 14, 14], dtype='object', name='level_0', length=105)

In [179]:
print(df.head())  # Shows the first few rows
print(df.columns)  # Shows the column names
print(df.index)  # Shows the index structure

level_0       0                    0                             0                            0                             0                             0                             0                     1                    1                             1                            1                             1                             1                             1                     2                    2                             2                            2                             2                             2                             2                     3                    3                             3                            3                             3                             3                             3                     4                    4                             4                            4                             4                             4                             4                     5        \
0                name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name
1             Bitcoin                      -0.0036                       -1.9001                      -1.1009                       -5.6085                        2.1515                       -1.9448      Ethereum                      -0.0965                       -2.5917                      -1.6000                      -16.4705                      -21.4543                      -21.7505           XRP                       0.1473                       -2.9283                      -7.9354                      -17.5951                       14.2242                       75.4545   Tether USDt                      -0.0046                       -0.0231                      -0.0219                        0.0737                        0.1362                       -0.1209           BNB                       0.6192                        0.4336                      -0.5508                       -4.4429                       -5.2333                       -1.2458        Solana
2        default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name

level_0              5                             5                            5                             5                             5                             5                     6                    6                             6                            6                             6                             6                             6                     7                    7                             7                            7                             7                             7                             7                     8                    8                             8                            8                             8                             8                             8                     9                    9                             9                            9                             9                             9                             9                     10                   10               \
0        quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h
1                             0.5503                       -1.7672                     -13.1209                      -31.0193                      -10.2144                      -33.3745          USDC                      -0.0109                        0.0044                      -0.0095                        0.0041                       -0.0024                        0.0040      Dogecoin                       0.3215                       -4.1804                     -12.8140                      -30.9368                      -24.7693                      -44.7076       Cardano                       0.3525                       -4.3043                      -4.8222                      -20.5845                      -15.7370                      -27.8990          TRON                      -0.3697                       -4.8136                       2.1341                       -4.1034                       -5.6530                       10.5521     Chainlink                       0.4011
2                       default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name

level_0               10                           10                            10                            10                            10                    11                   11                            11                           11                            11                            11                            11                    12                   12                            12                           12                            12                            12                            12                    13                   13                            13                           13                            13                            13                            13                    14                   14                            14                           14                            14                            14                            14
0        quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d          name  quote.USD.percent_change_1h  quote.USD.percent_change_24h  quote.USD.percent_change_7d  quote.USD.percent_change_30d  quote.USD.percent_change_60d  quote.USD.percent_change_90d
1                             -3.6772                     -10.2023                      -28.8407                      -27.3403                       -1.7167     Avalanche                       0.0102                        1.0179                      -5.4307                      -29.4109                      -34.9569                      -40.7418           Sui                       0.8569                       -5.0114                      -3.9385                      -23.6591                      -27.7722                       -3.0519       Stellar                       0.3482                       -2.9812                      -8.6568                      -21.7513                      -12.1381                      -44.8114      Litecoin                       0.9419                       -3.7883                      -0.5354                       13.9423                       21.2298                       27.3664
2                        default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name  default_name                 default_name                  default_name                 default_name                  default_name                  default_name                  default_name
Index([ 0,  0,  0,  0,  0,  0,  0,  1,  1,  1,
       ...
       13, 13, 13, 14, 14, 14, 14, 14, 14, 14], dtype='object', name='level_0', length=105)
RangeIndex(start=0, stop=3, step=1)

In [182]:
df = df.reset_index()
print(df.head())  # Check if it’s now structured correctly
df = df[df.iloc[:, 0] != "default_name"]  # Keep only actual data
df = df.T  # Transpose
df.columns = df.iloc[0]  # First row becomes the column names
df = df[1:].reset_index(drop=True)  # Remove the first row

ValueError: cannot insert level_0, already exists

In [183]:
df = df.reset_index(drop=True)

In [184]:
df = df[df.iloc[:, 0] != "default_name"]

In [185]:
if isinstance(df.columns, pd.MultiIndex):
    df.columns = ['_'.join(map(str, col)) for col in df.columns]

In [186]:
df.iloc[:, 1:] = df.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')

In [187]:
print(df.head())

level_0  level_0  index  0      0       0       0       0      0       0     1      1       1       1       1        1        1      2     2       2       2       2        2       2     3      3       3       3      3      3       3     4     4      4       4       4       4       4     5     5       5       5        5        5        5      6      6      6       6      6       6      6     7     7       7       7        7        7        7      8     8       8       8       8        8        8      9      9       9      9       9       9       9     10    10      10      10       10       10       10    11    11     11      11      11       11       11     12    12      12      12      12       12       12    13    13      13      13      13       13       13     14    14      14      14      14      14      14
0           0       0    NaN     NaN     NaN     NaN     NaN    NaN     NaN  NaN     NaN     NaN     NaN      NaN      NaN      NaN  NaN    NaN     NaN     NaN      NaN     NaN     NaN  NaN     NaN     NaN     NaN    NaN    NaN     NaN  NaN    NaN    NaN     NaN     NaN     NaN     NaN  NaN    NaN     NaN      NaN      NaN      NaN      NaN  NaN     NaN    NaN     NaN    NaN     NaN    NaN  NaN    NaN     NaN      NaN      NaN      NaN      NaN  NaN    NaN     NaN     NaN      NaN      NaN      NaN  NaN     NaN     NaN    NaN     NaN     NaN     NaN  NaN    NaN     NaN      NaN      NaN      NaN     NaN  NaN    NaN    NaN     NaN      NaN      NaN      NaN  NaN    NaN     NaN     NaN      NaN      NaN     NaN  NaN    NaN     NaN     NaN      NaN      NaN      NaN  NaN    NaN     NaN     NaN     NaN     NaN     NaN
1           1       1    NaN -0.0036 -1.9001 -1.1009 -5.6085 2.1515 -1.9448  NaN -0.0965 -2.5917 -1.6000 -16.4705 -21.4543 -21.7505  NaN 0.1473 -2.9283 -7.9354 -17.5951 14.2242 75.4545  NaN -0.0046 -0.0231 -0.0219 0.0737 0.1362 -0.1209  NaN 0.6192 0.4336 -0.5508 -4.4429 -5.2333 -1.2458  NaN 0.5503 -1.7672 -13.1209 -31.0193 -10.2144 -33.3745  NaN -0.0109 0.0044 -0.0095 0.0041 -0.0024 0.0040  NaN 0.3215 -4.1804 -12.8140 -30.9368 -24.7693 -44.7076  NaN 0.3525 -4.3043 -4.8222 -20.5845 -15.7370 -27.8990  NaN -0.3697 -4.8136 2.1341 -4.1034 -5.6530 10.5521  NaN 0.4011 -3.6772 -10.2023 -28.8407 -27.3403 -1.7167  NaN 0.0102 1.0179 -5.4307 -29.4109 -34.9569 -40.7418  NaN 0.8569 -5.0114 -3.9385 -23.6591 -27.7722 -3.0519  NaN 0.3482 -2.9812 -8.6568 -21.7513 -12.1381 -44.8114  NaN 0.9419 -3.7883 -0.5354 13.9423 21.2298 27.3664
2           2       2    NaN     NaN     NaN     NaN     NaN    NaN     NaN  NaN     NaN     NaN     NaN      NaN      NaN      NaN  NaN    NaN     NaN     NaN      NaN     NaN     NaN  NaN     NaN     NaN     NaN    NaN    NaN     NaN  NaN    NaN    NaN     NaN     NaN     NaN     NaN  NaN    NaN     NaN      NaN      NaN      NaN      NaN  NaN     NaN    NaN     NaN    NaN     NaN    NaN  NaN    NaN     NaN      NaN      NaN      NaN      NaN  NaN    NaN     NaN     NaN      NaN      NaN      NaN  NaN     NaN     NaN    NaN     NaN     NaN     NaN  NaN    NaN     NaN      NaN      NaN      NaN     NaN  NaN    NaN    NaN     NaN      NaN      NaN      NaN  NaN    NaN     NaN     NaN      NaN      NaN     NaN  NaN    NaN     NaN     NaN      NaN      NaN      NaN  NaN    NaN     NaN     NaN     NaN     NaN     NaN

In [191]:
df = df.reset_index(drop=True)  # Avoid inserting duplicate index columns
df = df.dropna(how='all')  # Drop rows where all values are NaN
df = df.loc[:, ~df.columns.duplicated()]  # Remove duplicate column names
df = df.drop(columns=["level_0", "index"], errors='ignore')  # Drop specific unwanted columns
print(df.head())  # Verify structure

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Index: []

In [192]:
print(df.shape)  # Check if it has rows/columns before processing
print(df.info())  # Inspect data types and null values

(0, 15)
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       0 non-null      object
 1   1       0 non-null      object
 2   2       0 non-null      object
 3   3       0 non-null      object
 4   4       0 non-null      object
 5   5       0 non-null      object
 6   6       0 non-null      object
 7   7       0 non-null      object
 8   8       0 non-null      object
 9   9       0 non-null      object
 10  10      0 non-null      object
 11  11      0 non-null      object
 12  12      0 non-null      object
 13  13      0 non-null      object
 14  14      0 non-null      object
dtypes: object(15)
memory usage: 0.0+ bytes
None

In [193]:
df

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Index: []

In [11]:
# redo bc
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
#Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'15',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  #print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

#NOTE:
# I had to go in and put "jupyter notebook --NotebookApp.iopub_data_rate_limit=1e10"
# Into the Anaconda Prompt to change this to allow to pull data

# If that didn't work try using the local host URL as shown in the video



type(data)
import pandas as pd


#This allows you to see all the columns, not just like 15
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
#This normalizes the data and makes it all pretty in a dataframe

df = pd.json_normalize(data['data'])
df['timestamp'] = pd.to_datetime('now')
df
def api_runner():
    global df
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
    #Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    parameters = {
      'start':'1',
      'limit':'15',
      'convert':'USD'
    }
    headers = {
      'Accepts': 'application/json',
      'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
    }

    session = Session()
    session.headers.update(headers)

    try:
      response = session.get(url, params=parameters)
      data = json.loads(response.text)
      #print(data)
    except (ConnectionError, Timeout, TooManyRedirects) as e:
      print(e)

In [ ]:
#redo 


#NOTE:
# I had to go in and put "jupyter notebook --NotebookApp.iopub_data_rate_limit=1e10"
# Into the Anaconda Prompt to change this to allow to pull data
    
    # Use this if you just want to keep it in a dataframe
df2 = pd.json_normalize(data['data'])
df2['Timestamp'] = pd.to_datetime('now')
df = pd.concat([df, df2], ignore_index=True)



    # Use this if you want to create a csv and append data to it
    #df = pd.json_normalize(data['data'])
    #df['timestamp'] = pd.to_datetime('now')
    #df

    #if not os.path.isfile(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv'):
        #df.to_csv(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv', header='column_names')
    #else:
        #df.to_csv(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv', mode='a', header=False)
        
    #Then to read in the file: df = pd.read_csv(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv')

# If that didn't work try using the local host URL as shown in the video


import os 
from time import time
from time import sleep

for i in range(333):
    api_runner()
    print('API Runner completed')
    sleep(60) #sleep for 1 minute
exit()
df

# One thing I noticed was the scientific notation. I like it, but I want to be able to see the numbers in this case

pd.set_option('display.float_format', lambda x: '%.5f' % x)

API Runner completed
API Runner completed
API Runner completed
API Runner completed

In [ ]:
# chatgpt code to above one 
import os
import pandas as pd
from time import sleep
from datetime import datetime

# Initialize an empty list to store DataFrames
df_list = []

# Define API Runner function
def api_runner():
    global df_list  # Ensure we modify df_list inside the function
    data = fetch_api_data()  # Replace with actual API call function
    
    if data and 'data' in data:
        df2 = pd.json_normalize(data['data'])
        df2['Timestamp'] = datetime.now()  # Use datetime.now() for efficiency
        
        # Append to list instead of directly concatenating to df
        df_list.append(df2)
    
    print(f"API Runner completed at {datetime.now().strftime('%H:%M:%S')}")

# Run the API Runner function fewer times
for i in range(10):  # Reduced iterations from 333 to 10
    api_runner()
    sleep(10)  # Reduced sleep time (adjust as needed)

# Combine all collected data once at the end
df = pd.concat(df_list, ignore_index=True)

# Save data to CSV only once to improve performance
csv_path = r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv'
df.to_csv(csv_path, index=False, mode='a', header=not os.path.exists(csv_path))

# Display first few rows
print(df.head())

# Ensure numbers are displayed in readable format
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [ ]:

df

In [ ]:
# Now let's look at the coin trends over time

df3 = df.groupby('name', sort=False)[['quote.USD.percent_change_1h','quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d']].mean()
df3

In [ ]:

df4 = df3.stack()
df4

In [ ]:
type(df4)

In [ ]:
df5 = df4.to_frame(name='values')
df5

In [ ]:
df5.count()

In [ ]:
#Because of how it's structured above we need to set an index. I don't want to pass a column as an index for this dataframe
#So I'm going to create a range and pass that as the dataframe. You can make this more dynamic, but I'm just going to hard code it


index = pd.Index(range(90))

# Set the above DataFrame index object as the index
# using set_index() function


# If it only has the index and values try doing reset_index like "df5.reset_index()"

In [ ]:

df7 = df6.rename(columns={'level_1': 'percent_change'})
df7

In [ ]:
df7['percent_change'] = df7['percent_change'].replace(['quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d'],['24h','7d','30d','60d','90d'])
df7

In [ ]:
#chatgpt

In [ ]:
print(df7.columns)

In [ ]:
df7['percent_change'] = df7.get('percent_change', pd.Series()).replace(
    ['quote.USD.percent_change_24h', 'quote.USD.percent_change_7d', 
     'quote.USD.percent_change_30d', 'quote.USD.percent_change_60d', 
     'quote.USD.percent_change_90d'], 
    ['24h', '7d', '30d', '60d', '90d']
)

In [ ]:
df7.columns = df7.columns.str.strip()
print(df7.columns)  # Check if the correct name exists

In [ ]:
print(df7.head())  # Check available data
print(df7.info())  # Check non-null counts
print(df7.head())  # See sample data

In [ ]:
print(df6['percent_change'].isna().sum())  # Count NaN values
print(df6.head())  # Check data before renaming

In [ ]:
print(df6.columns)  # See correct column names

In [3]:
# Step 1: Group by 'name' and calculate mean for selected columns
df3 = df.groupby('name', sort=False)[[
    'quote.USD.percent_change_1h',
    'quote.USD.percent_change_24h',
    'quote.USD.percent_change_7d',
    'quote.USD.percent_change_30d',
    'quote.USD.percent_change_60d',
    'quote.USD.percent_change_90d'
]].mean()

# Step 2: Stack the DataFrame to reshape it
df4 = df3.stack()

# Step 3: Convert stacked Series to DataFrame with column name 'values'
df5 = df4.to_frame(name='values')

# Step 4: Reset index to create columns
df6 = df5.reset_index()

# Step 5: Rename the level_1 column to 'percent_change'
df7 = df6.rename(columns={'level_1': 'percent_change'})

# Step 6: Replace long column names with shorter timeframes
df7['percent_change'] = df7['percent_change'].replace({
    'quote.USD.percent_change_24h': '24h',
    'quote.USD.percent_change_7d': '7d',
    'quote.USD.percent_change_30d': '30d',
    'quote.USD.percent_change_60d': '60d',
    'quote.USD.percent_change_90d': '90d'
})

# Final DataFrame
print(df7.head())

NameError: name 'df' is not defined